### ISSUE TITLE
unable to bind new command under `flycheck-mode-map` or `flycheck-command-map`

### ISSUE THREAD

**Issue by magicdirac** [flycheck/flycheck#1001]
Hello, I write an avy interface package [`avy-flycheck`](https://github.com/magicdirac/avy-flycheck) for flycheck syntax errors naviagation.  
I intend to bind this new command to `C-c ! g` as below 
```elisp
(define-key flycheck-mode-map (kbd "C-c ! g") #'avy-flycheck-goto-error)
```
However, that does not work, can you help me how to do that?

**Comment by cpitclaudel** [comment]
Hi,

Can you try `M-x where-is RET avy-flycheck-goto-error RET` after running the `define-key` above? What does that print?

**Comment by magicdirac** [comment]
```
(require 'flycheck)
(require 'avy-flycheck)
(define-key flycheck-mode-map (kbd "C-c ! g") #'avy-flycheck-goto-error)
```
and then run
`M-x where-is` `avy-flycheck-goto-error` it returns
```
You can run the command ‘where-is’ with C-h w
avy-flycheck-goto-error is not on any key
```

**Comment by cpitclaudel** [comment]
> I update the binding function to check whether flycheck has been loaded or not.
sounds like it works wells.

I think you could simplify this code. Assuming your package depends on flycheck, there'll be a `(require 'flycheck)` somewhere in that file. Since that function is autoloaded, the require will be run before the function. Thus `(define-key ...)` should be enough (regardless of this, the `if` part is useless; see the docs of `with-eval-after-load`)

> BTW: The package checks flycheck overlays and list them as candidates for user's selection.
However I noticed that it would get some false positives for the candidates.
for example, if the point is on a bracket of a line with a flycheck overlay. then the overlay-list will return 3 candidates for this line. one for the flycheck overlay, two for the highlighted paired brackets.
Do you know how to address this false positives for the candidates? 

Yes, I think so: use `flycheck-overlays-in` and `flycheck-overlays-at` instead of `overlays-in` and `overlays-at`. Does this help?

**Comment by magicdirac** [comment]
Thank you!
