### ISSUE TITLE
Compiler Macro error in `make compile`

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1009]
#973 has broken `make compile` on Emacs 25:

```console
$ make clean compile
rm -rf flycheck.elc flycheck-buttercup.elc flycheck-ert.elc
/Library/Developer/CommandLineTools/usr/bin/make -C doc clean
rm -rf _build/*
cask exec emacs -Q --batch -L .  -f batch-byte-compile flycheck.el
Compiler-macro error for flycheck-syntax-check-new: (wrong-type-argument stringp (flycheck-compute-default-directory checker))
cask exec emacs -Q --batch -L .  -f batch-byte-compile flycheck-buttercup.el
cask exec emacs -Q --batch -L .  -f batch-byte-compile flycheck-ert.el
```

Note this `wrong-type-argument` error.

@sergv Would you please take a look at this error on Emacs 25?  Broken byte compilation is a serious issue; if we can't get this fixed I'll have to revert #973.

**Comment by sergv** [comment]
This looks like pretty strange error at the crossing point of macro definitions and byte compilation. I'll investigate.

**Comment by sergv** [comment]
Well, the problem turns out to be particularly simple. The `default-directory` variable is defined directly in C and has `stringp` predicate attached to it. One cannot assign anything but strings into it.

Next, this variable is special, so it has dynamic scope. Thus, when binding it via `let` the single memory cell gets assigned and this cell cannot contain anything but strings. Alas, `cl-defstruct` macro expands into `let` that binds the `default-directory` variables. It binds it to unevaluated expression `(flycheck-compute-default-directory checker)`, but variable must contain strings only, so the error is thrown.

This is pretty unfortunate interaction between internal C variable, dynamic scope and compiler macros.

So, the solution is to rename the default-directory field of `flycheck-syntax-check` structure. How about naming it `working-directory` and renaming all mentions of `default-directory` into `working-directory` for consistency?

**Comment by lunaryorn** [comment]
@sergv Oh dear, thanks for sorting this mess out 😳 

I think renaming default-directory to working-directory is a good idea.  For the sake of consistency I'd use the new wording everywhere, in the struct as well as in syntax checker definitions and properties.

I'd be great if you could open a corresponding PR.
