### ISSUE TITLE
Include relevant patches from Debian

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1077]
See https://anonscm.debian.org/git/pkg-emacsen/pkg/flycheck.git/tree/debian/patches for their patches, and take what we can integrate.

# Patches

- [x] `clear-GPG-agent-env-vars.patch` – seems to be redundant?
- [ ] `disable-MELPA-tests.patch`
- [ ] `disable-rpmlint-test.patch`
- [ ] `disable-sqlint-test.patch`
- [x] `fix-autoload-tests.patch`
- [ ] `fix-flake8-expected-values.patch`
- [x] ~~`patch-README-for-Debian.patch`~~ – won't upstream, we need our README the way it is for Github
- [x] `patch-test-runner.patch` – can we upstream that somehow? Yes, we can, in a different way: Let's load deps and libraries in the makefile, and let the runner just, well, run the suite.
- [x] ~~`remove-references-to-legacy-manual.patch`~~ (see #924)
- [x] `remove-todolist.patch`
- [x] `set-epg-gpg-home-directory.patch` – seems to be redundant?
- [x] `use-gpg1.patch` – I refactored the gpg tests to use gnupg21 and Emacs25, to make them work on my system again.  The test is automatically skipped for earlier versions of gpg or emacs.

----

@spwhitton I haven't taken a closer look yet, but I'll probably have a couple of questions about patches. Would it be ok if I mentioned you here if something pops up about a patch there?

**Comment by spwhitton** [comment]
Of course.  I've already forwarded the ones that are easily mergeable.
Happy to answer questions about the others.

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@spwhitton I've removed the todolist from the manual, which should make `remove-todolist.patch` superfluous.

**Comment by lunaryorn** [comment]
@spwhitton May I ask why you comment the tests you'd not like to run?  Are you aware that you can select the tests to run?  For instance `make ERTSELECTOR='(not (checker rpm-rpmlint))' integ` will skip the rpmlint tests.

**Comment by lunaryorn** [comment]
@spwhitton Please see the list of patches in my original post—the checked ones are the ones I included.

**Comment by lunaryorn** [comment]
Regarding `patch-test-runner.patch` can we somehow change our runner to make that patch redundant?  Could you cast a little light on how you run the tests in the Debian package?

**Comment by lunaryorn** [comment]
Regarding `clear-GPG-agent-env-vars.patch` and `set-epg-gpg-home-directory.patch`, I don't think these are needed anymore.  As far as I know there are no GPG tests left in `flycheck-test.el`; they were all moved to buttercup specs in `test/specs/test-util.el`.

**Comment by spwhitton** [comment]
1. I wasn't aware of `ERTSELECTOR`.  Is that part of ERT, or is it implemented in flycheck?  We don't use your Makefile to run the test suite, so we can't use it if it's specific to flycheck.  It would be great to drop those patches if possible, though.

2. W.r.t. `patch-test-runner.patch`: good question.  Our test runner finds all files containing ERT tests, and loads them.  Then it calls `flycheck-run-tests-main`.  That function complains if the files are already loaded.  Why is it a problem to load them twice?  Maybe that function doesn't need to complain.

3. W.r.t. `clear-GPG-agent-env-vars.patch` and `set-epg-gpg-home-directory.patch`: thanks for letting me know.  I'll see what happens if I drop them.

4. `use-gpg1.patch`: so I can drop this patch, and the tests will be skipped until Emacs 25 hits Debian?

Thanks!

**Comment by lunaryorn** [comment]
1. Selectors are part of ERT, but the Makefile option and the special selectors are our code.
2. I'm not aware that `flycheck-test` would complain—it doesn't explicitly do so.  Could you show me the error message?
3. (markdown, don't spoil my numbers :) )
4. Yes, this test now requires Emacs 25.1 for the new epa functions and gpg 2.1 because it's the version with the most predictable behaviour.  Is skipping the test ok for you?  I saw that you used gpg 2.1 already, and given that Emacs 25.1 is out now, I figured that it's probably not worth bothering with older versions.

Out of curiosity, why do you use a custom ERT runner for our tests?  Can we make changes so that you can use our makefile (as in `make unit integ`)?  I wasn't aware that anyone used the test runner directly and I'm not sure whether I'm happy about it.  

How do you run the specs?  Do you have a custom runner, too?

**Comment by spwhitton** [comment]
Hello,

On Sun, Sep 18, 2016 at 02:08:14AM -0700, Sebastian Wiesner wrote:
>  1. Selectors are part of ERT, but the Makefile option and the special
>     selectors are our code.

Okay.  I'll look into this more.

>  2. I'm not aware that flycheck-test would complain—it doesn't
>  explicitly do so. Could you show me the error message?  

The error I was seeing was `(error "Test suite already initialized")` in
`flycheck-ert.el`.

> 4. Yes, this test now requires Emacs 25.1 for the new epa functions
> and gpg 2.1 because it's the version with the most predictable
> behaviour. Is skipping the test ok for you? I saw that you used gpg
> 2.1 already, and given that Emacs 25.1 is out now, I figured that it's
> probably not worth bothering with older versions.

Yes, that's fine, since Emacs 25 is out.

> Out of curiosity, why do you use a custom ERT runner for our tests? Can we make
> changes so that you can use our makefile (as in make unit integ)? I wasn't
> aware that anyone used the test runner directly and I'm not sure whether I'm
> happy about it.

I would definitely prefer to use `make unit integ` but your Makefile
requires Cask, which we don't want to package for Debian (because we
already have a package manager!).

> How do you run the specs? Do you have a custom runner, too?

We have a perl script called `dh_elpa_test`.  It uses some heuristics to
try to guess how to run the test suite, and it has a config file to give
hints.  Buttercup is easy.  For ERT, this is *roughly* what it does:

    emacs --batch -Q \
           	-L . -L test \
    	--eval "(progn (require 'package) (add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa-src\"))" \
    	-f package-initialize \
    	-l test/run.el

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@spwhitton Ah, I forgot about that.  Yep, `flycheck-test` doesn't allow being loaded twice.  I guess we could lift that restriction, but I'd rather like for Debian to use our `Makefile` to run the tests if possible.  It's just easier for us to maintain a single entry point for our test suite.

Note that following #1032 our Makefile does not require `Cask` anymore.  You could replace your invocation with `make CASK= EMACSOPTS='--eval "(progn (require 'package) (add-to-list 'package-directory-list \"/usr/share/emacs/site-lisp/elpa-src\"))"' unit integ` as far as I can see.  We'll not try to use Cask anymore if `CASK` is undefined when invoking the Makefile.

Would it be possible for Debian to use our Makefile that way?

**Comment by spwhitton** [comment]
Thank you for the sample `make` invocation.  It's good to hear that cask
is no longer a hard requirement.  Unfortunately, there is one further
requirement that I neglected to mention previously.

We run the test suite in two places: during the package build, and on
ci.debian.net.  When the tests are run during the package build, they
use the uninstalled copy of flycheck.el.  However, when they are run on
ci.debian.net, it is required that they use the copy of flycheck.el from
/usr/share.  This is so we can test flycheck as it would be installed
on a user's system.

To achieve this, our dh_elpa_test script renames flycheck.el to
flycheck.disabled.  That way, we can be sure that the tests are run
against the copy in /usr/share.

So in order to use the Makefile, we would need some other way to ensure
that the copy of flycheck.el in the source tree was disabled *only* when
running on ci.debian.net.  I don't think it would be wise for you to try
to reimplement that in your Makefile.  We already wrote dh_elpa_test,
and it is a waste of time to make a flycheck-specific version.

So I think it would be best to just keep the current situation -- either
lift the restriction (why is there that restriction?) or just keep the
patch as Debian-specific.

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@spwhitton That's not so much a restriction, as rather a precaution.  As you typically don't load test suites twice, doing so may indicate a configuration error.

I'd not like to lift the restriction, as I think it's helpful to prevent such errors, but I think we can move loading these files up into the makefile so that the runner itself would not load them anymore.  In the past we allowed to use the runner independently (i.e. `sh test/run.el`) so loading them at this place was convenient, but nowadays we really encourage the Makefile so I guess we should really decouple loading from running now.

I'll do that.

**Comment by lunaryorn** [comment]
@spwhitton `test/run.el` no longer loads the test libraries directly so you should be able to remove the patch to the test runner.

**Comment by lunaryorn** [comment]
I guess that's all we can change… it doesn't look as if the patches to the tests can be upstreamed.  @spwhitton What do you think?

**Comment by lunaryorn** [comment]
PS: I removed the todolist from the manual so that patch is also redundant.

**Comment by spwhitton** [comment]
On Sat, Sep 24, 2016 at 04:14:23AM -0700, Sebastian Wiesner wrote:
> @spwhitton test/run.el no longer loads the test libraries directly so you
> should be able to remove the patch to the test runner.

Okay, thanks, I'll do that upon the next release.

On Sat, Sep 24, 2016 at 04:16:15AM -0700, Sebastian Wiesner wrote:
> I guess that's all we can change… it doesn't look as if the patches to the
> tests can be upstreamed. @spwhitton What do you think?

Which patches do you mean?  I thought that I had already submitted pull
requests for all patches to the actual tests.

On Sat, Sep 24, 2016 at 04:16:54AM -0700, Sebastian Wiesner wrote:
> PS: I removed the todolist from the manual so that patch is also redundant.

Great -- I've made a note to do this on the next release.

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@spwhitton I meant the patches that comment tests to disable them, e.g. `disable-MELPA-tests.patch`

**Comment by spwhitton** [comment]
On Tue, Sep 27, 2016 at 01:34:50AM -0700, Sebastian Wiesner wrote:
> @spwhitton I meant the patches that comment tests to disable them, e.g.
> disable-MELPA-tests.patch

Right.  The "Forwarded: not-needed" indicates that they are
Debian-specific.

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@spwhitton Ah, nice.  I'm impressed by how well Debian manages patches 😮 

I'm closing this issue, many thanks for your efforts and for your contributions!

**Comment by spwhitton** [comment]
On Wed, Sep 28, 2016 at 02:26:16AM -0700, Sebastian Wiesner wrote:
> @spwhitton Ah, nice. I'm impressed by how well Debian manages patches 😮

Per the Debian Social Contract, "We will communicate things such as bug
fixes, improvements and user requests to the "upstream" authors of works
included in our system."

:)

-- 
Sean Whitton
