### ISSUE TITLE
Flycheck false positives on free variables

### ISSUE THREAD

**Issue by PeppermintHippo** [flycheck/flycheck#1143]
how does flycheck determine if a function or variable is free in a source file? I set up a .dir-locals.el and setup correctly irony mode for company and (for the most part) flycheck but certain variables are showing "free" or "undeclared" errors when they are really just defined in a different file in the same project, (albeit not necessarily the same directory).

I tried the troubleshooting guide but I couldn't activate the flycheck package after starting emacs -Q, ( I think spacemacs complicates the activation of the package). 
I am using spacemacs on windows on a usb (not sure of that matters). I know windows is not officially supported but maybe if someone can give me some advice on how flycheck tests if a function is already defined or not maybe I can fix this myself.
Then again maybe this is a problem with irony but in any case I am hoping someone here can point me in the right direction.
Thanx

**Comment by cpitclaudel** [comment]
Hi there,

This is not a Flycheck problem: actual error detection is done by thrid-party tools, and we just display their results (you can think of Flycheck as a wrapper around linters and syntax checkers).  The specific errors depend on the actual checker that you're using.

Hope this helps!

**Comment by lunaryorn** [comment]
@PeppermintHippo Presuming that you refer to free variables in Emacs Lisp Flycheck doesn't do anything by itself, as @cpitclaudel noted.  It simply uses the Emacs Lisp byte compiler, i.e. a slightly more sophisticated equivalent of `emacs -Q --batch -f batch-byte-compile <filename>`.  Essentially it tries to compile the file in a clean Emacs session.  To avoid free variables the file needs to `defvar` all variables or `require` the libraries that define them.  

It's long since I used spacemacs, but if I remember correctly its layers don't really care about requiring libraries and defining variables properly, so free variables are to be expected with Spacemacs.  In any case if you find free variable warnings in Spacemacs' own sources that's to be brought up with the Spacemacs maintainers; Flycheck can't do anything about it.

But I'm not sure how Irony Mode is relevant here?  Irony Mode has nothing to do with Emacs Lisp; it's for C++.  Or are we talking about warnings in C/C++?

**Comment by PeppermintHippo** [comment]
Yeah I'm working with c atm. Does that change the solution you propose?

**Comment by lunaryorn** [comment]
@PeppermintHippo Sorry, but you've lost me now: Do you get the warnings in C code or in Emacs Lisp code?

Please try to be more specific, to help us understand where the problem is.

**Comment by PeppermintHippo** [comment]
Working on a c code project. Flycheck is linting a free variable that is defined in a different file in the same directory or subdirectory.

**Comment by lunaryorn** [comment]
@PeppermintHippo I'm sorry but that's not at all specific.  Could you please show an example of the warnings that you see?  Please, try to put more effort in your comments and provide _detailed_ and _specific_ information, at best including some example of the behaviour you see.

**Comment by PeppermintHippo** [comment]
Will do, I'll give an update after work today :)

**Comment by PeppermintHippo** [comment]
Think I know the issue now, it is definitely with irony.

Using the right includes in a .clang_complete file solved the issue.

Lessons learned:
For others with similar issues...
one of my errors were
[image: pasted3]
neither flycheck nor company could find this despite my dir-locals
containing

(eval . (progn (require 'projectile)
                (setq company-clang-arguments (delete-dups (append
company-clang-arguments
                    (list
(concat usb-drive-letter "Programming/msys64/mingw64/lib/glib-2.0/include/")
(concat usb-drive-letter "Programming/msys64/mingw64/include/glib-2.0/")
))))))

...similiar entry for flycheck-clang-include-path variable...

but simply creating a .clang_complete file with

-IE:\Programming\msys64\mingw64\include\glib-2.0

as the only entry was enough to fix this.

I am guessing the point of defining flycheck-clang-include-path variable is
for people not using irony? Maybe it should be pointed out in the
documentation that this is the case. Albeit, admittedly I should have known
this from the irony documentation.
Anyway thanks for the support!
