### ISSUE TITLE
Add an option to check rust project with cargo clippy

### ISSUE THREAD

**Issue by dzamlo** [flycheck/flycheck#1154]
`clippy` is a collection of additional lints for the rust programming language. A cargo project can be checked by running `cargo clippy`. In addition to adding more lints, `cargo clippy` will check the examples, the tests and all the binaries.

I think than an option to use it with flycheck would be a good idea.

For the implementation, running `cargo clippy` instead of `cargo rustc`, without the `--lib` or `--bin` option seems to work. I think the `--test` option should not be used with cargo clippy.

**Comment by cpitclaudel** [comment]
Hi Loïc,

Do you think you could write the corresponding checker definition? It would probably share a lot with the `rustc` one, so it should be rather straightforward :)

**Comment by dzamlo** [comment]
Yes, I can try. 
Do you think it should be a new checker, or an option that modify the behavior of the rust-cargo checker ?

**Comment by cpitclaudel** [comment]
My vote would go to new checker, but @flycheck/rust will certainly have a more relevant opinion :)
The nice part of making it a separate checker is that it is discoverable and configurable just like all other checkers.

**Comment by cpitclaudel** [comment]
On the other hand, if it's a strict superset of `rustc` in terms or errors reported, then it probably shouldn't be a separate checker (i.e., if it does `rustc` + more checks, then it could just be an option)

**Comment by fmdkdd** [comment]
I've never used `clippy`, but it's a linter,  so I expect it to give linting errors only, and not compilation errors.  And the output format seems "classical" (i.e., not JSON), so it wouldn't be compatible with the current `rust` or `rust-cargo` checkers.  I think a new checker will be best :)

@dzamlo The current rust checkers might not be the best examples to base yours upon, as we parse the errors from the JSON output rather than the plain text stdout.  You can look at other linters to get an idea, or at the [previous versions](https://github.com/flycheck/flycheck/blob/00a38359bf12fb004276a878731382685a480247/flycheck.el#L8276-L8311) of the rust checkers to get an idea.

Feel free to ask questions if any arise :)

**Comment by lunaryorn** [comment]
It's a separate tool, so I think we should have a separate checker.

**Comment by dzamlo** [comment]
`cargo clippy` will actually give you the errors that `cargo rustc` will give you, but will give you some more warnings. It is a strict superset of the `cargo rustc` in terms of errors reported.

As far as I understand, the tool will do the same thing that `cargo rustc`, but will add some options to use the clippy lints and compile both as test and none test, will check the examples, etc.

Anyways, I made a separate checker and will send a pull request very soon.

**Comment by fmdkdd** [comment]
Then it works not at all like I expected it would.  Looking at the source, it seems it registers lints as extra passes to the compiler, and the compiler takes care of diagnostics formatting.  Nifty.

So it will definitely have some overlap with the `rust-cargo` checker, but it's better than having convoluted tests in just one checker and multiple commands (`cargo rustc/clippy`).

**Comment by cpitclaudel** [comment]
Done in #1385
