### ISSUE TITLE
Emacs lisp use-package support

### ISSUE THREAD

**Issue by eflanigan00** [flycheck/flycheck#1172]
Emacs 25.1.1
It is saying assignment to free variable but that variable is in bm

    (use-package bm                     ;;; Visual Bookmarks
      :init
      (setq bm-restore-repository-on-load t)  ;; restore bm on load

**Comment by lunaryorn** [comment]
:init runs before load; the variable is still undefined at this time.  Looking at the name of the variable :config won't help I guess, but you can use :defines to define the variable explicitly.

That's not an issue in Flycheck, though, so I'm closing this.

**Comment by lunaryorn** [comment]
You do not need :defines for variables in :config, as long as these variables are defined in the library.  In Helm that's often not the case though since many variables are defined in other libraries like helm-files.el and not in helm.el itself.  

But again, it's not Flychecks fault, it's just how libraries work in Emacs Lisp.

**Comment by eflanigan00** [comment]
This gets rid of bm-restore-repository-on-load so thank you for that.
But config behaviour is still confusing to me, flycheck doesn't like bm-buffer-save
 
    (defvar bm-restore-repository-on-load)
    (use-package bm                     ;;; Visual Bookmarks
      :init
      (setq bm-restore-repository-on-load t)  ;; restore bm on load
      :functions
      bm-buffer-save
     :config
      (add-hook 'kill-buffer-hook #'bm-buffer-save))    ;; Saving bookmarks
