### ISSUE TITLE
flycheck-executable-find with a long-running function

### ISSUE THREAD

**Issue by Profpatsch** [flycheck/flycheck#1183]
I have a setup in which a compiler is *generated* on a per-project basis and dependencies are resolved automatically on-the-fly. (More specific: I use the `nix` package manager and it constructs a `ghc` that knows the package database for the current project.)

This process might take anywhere from .5 seconds to 10 minutes, depending on whether dependencies still have to be downloaded or even compiled. In that time the whole editor freezes, since `flycheck-executable-find` is synchronous.

Maybe there is a better way to set that up? I’d preferably have a temporary buffer that displays the output of the package manager as it runs.

**Comment by fmdkdd** [comment]
What value do you use for `flycheck-executable-find`?

I'm not familiar with `nix`, but the default value of `executable-find` will just search through a list of directories, and I'm not seeing how it can trigger the package manager to download dependencies.

**Comment by Profpatsch** [comment]
```elisp
        flycheck-executable-find
          (lambda (cmd) (nix-executable-find (nix-current-sandbox) cmd)))
```

This calls the nix package manager, which proceeds to download/compile dependencies if they are not yet locally available.

**Comment by fmdkdd** [comment]
Thanks for the clarification.  I don't think we want to tweak `flycheck-executable-find` to work asynchronously, since running the checkers depends on knowing the executables, it would mean starting the checkers asynchronously as well... asynchronous changes like this are pervasive, and would benefit only a few users.  For that reason, I'm leaning on wontfix.  But maybe @cpitclaudel feels it can be done :)  Or, if you make a PR, we can discuss it.

Now, for your situation, can you maybe start `nix` asynchronously yourself in `flycheck-executable-find` with `make-process`?  That way you can direct the output to a buffer and check the progress.  If you return `nil` in `flycheck-executable-find`, the checker will fail to run, and will probably be disabled.  You can re-enable it when `nix` has finished installing, even automatically by specifying a `:sentinel` to `make-process`.

If you do get it working the way you want, please share it; other nix users may find it useful as well.

**Comment by Profpatsch** [comment]
That’s very helpful, thanks!

**Comment by cpitclaudel** [comment]
@fmdkdd I agree fully. As far as Flycheck is concerned, this checker isn't installed yet; find-executable should return `nil` and possibly launch a background process to build the relevant checker, and once that process completes its sentinel should enable the checker :)

The background process could also be launched from a find-file hook, or even a flycheck-mode hook.

@Profpatsch Let us know if you need further tips!
