### ISSUE TITLE
Further options for tslint

### ISSUE THREAD

**Issue by Ailrun** [flycheck/flycheck#1184]
When I use tslint with type-check-required rules, I need to give some options like `--project <path/to/tsconfig.json> --type-check`.

But at least I try, there is no way to give such options to flycheck-typescript-tslint.

Is there any way to do so?
If not, could you add some customizable variable for this?

**Comment by fmdkdd** [comment]
Can you checkout the branch at #1186 and see if that works for you?

**Comment by Ailrun** [comment]
@fmdkdd Thx for ur fix!

**Comment by fmdkdd** [comment]
@Ailrun You're welcome.  Happy hacking.

**Comment by jupl** [comment]
I've been spending hours trying to get this to work with `--project` and `--type-check`. Is there any working example of `flycheck-tslint-args`?

**Comment by cpitclaudel** [comment]
@jupl Did you use the customize interface? You can just insert the arguments there, one by one.

**Comment by lddubeau** [comment]
@cpitclaudel Using the customize interface won't cut it. `tslint` has some rules that require checking types. If we use such rules, we need to use `--type-check` *and* `--project <path-to-project>` when running `tslint`. The issue though is that `--project` will change depending on which file needs to be edited. Most of us have multiple different packages we work on that are independent from one another and consequently are all different projects. Actually, it is not rare for a *single* package to contain *multiple* TypeScript projects (e.g. the main code is governed by one project whereas the testing code is governed by another). To work around the issue I've defined a custom checker:

    (defvar flycheck-typescript-tslint-project "tsconfig.json")
    (flycheck-define-checker typescript-tslint-ldd
      "Redefine the tslint checker to handle --type-check."
      :command ("tslint" "--format" "json"
                (config-file "--config" flycheck-typescript-tslint-config)
                (option "--rules-dir" flycheck-typescript-tslint-rulesdir)
                (config-file "--project" flycheck-typescript-tslint-project)
                (eval flycheck-tslint-args)
                ;; Must use inplace to satisfy paths in project.
                source-inplace)
      :error-parser flycheck-parse-tslint
      :modes (typescript-mode))

I've put `--type-check` in my `flycheck-tslint-args`. When `--type-check` is used, `--project ...` must also be used to avoid getting an error or making `--type-check` a noop. (Whether you get an error or a noop varies depending on which version of `tslint` you use.) Moreover, when a project is used, the file passed to `tslint` must be passed through `source-inplace` because `tslint` uses the patterns in the project passed and if the file is not among those that project includes in its list of files, then you get a (rather misleading) error like this:

```
Invalid source file: /tmp/.../foo.ts. Ensure that the files supplied to lint have a .ts, .tsx, .js or .jsx extension.
```

My tests suggest that when `--project` is passed without `--type-check`, then `--project` is ignored, because in the tests I ran manually to get the error above, if I remove `--type-check` but still specify a project, then the error is not raised, suggesting that the project is is ignored.

**Comment by lddubeau** [comment]
I've just discovered that `source-inplace` may not be good enough. In general it works fine but there's one type of scenario where it does not work. In order to produce an issue report for `tslint` I produced a file that contained a function `foo` and the file was not importing or exporting anything. Something like `function foo(): void { /* something */ }` Using `source-inplace`, `flycheck` creates a temporary file of the same name but with the `flycheck` prefix. The problem is that when `tslint` asks TypeScript to get type information (because of `--type-check`), TypeScript sees both the original and the temporary file and declares that `foo` has a duplicate definition. That's because since neither the original file nor the temporary file contain `import` or `export`, they are considered to be "scripts" and everything they declare at the top level of execution is global. So TypeScript sees a global `foo` in the original file and in the temporary file and errors.

I don't see a solution other than using `source-original` with an appropriate `:predicate`.
