### ISSUE TITLE
Eslint config file missing

### ISSUE THREAD

**Issue by peteyy** [flycheck/flycheck#1195]
flycheck-verify-setup output:

```
javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at /Users/peteyy/Projects/.../node_modules/eslint/bin/eslint.js
    - config file: missing
```

I'm using .eslintrc.yaml extension and in most other editors that I've used recently (Webstorm and Atom) it picks it up fairly well.

`/Users/peteyy/Projects/.../node_modules/eslint/bin/eslint.js --print-config .`

returns a valid configuration file that corresponds to what I have set in the .eslintrc.yaml file.

If there is a quick workaround for setting the config file (after about half an hour googling I haven't found one) I have seen issues about eslint versions so just to make sure my version is: 

`/Users/peteyy/Projects/.../node_modules/eslint/bin/eslint.js --version`
`v3.13.0`

**Comment by Simplify** [comment]
Hi @peteyy,
Thank you for your report.

There is no option to set configuration file, because we relay on ESLint to find it. We had [similar issue before](https://github.com/flycheck/flycheck/issues/1155). Please check your `$PATH` in Emacs. If you are on macOS, please install [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) package. 

Let us know if this helps.

**Comment by peteyy** [comment]
@Simplify Thanks for the advice it helped! :) I thought I'd only need that if I'm using the global eslint.

**Comment by Simplify** [comment]
@peteyy no problem, I'm glad it helped :)

**Comment by mikhail-krainik** [comment]
Hi everyone.
I have a same problem, but I use linux and your advice about PATH certain macOS? 
Which information should I provide for resolve my issue?

**Comment by Simplify** [comment]
@mikhail-krainik if your `eslint` is in `node_modules/.bin` check [this issue](https://github.com/flycheck/flycheck/issues/1155), last two comments.
If your Emacs in X does not load $PATH from `.profile` or `.bash_profile`, `exec-path-from-shell` package works on GNU/Linux also.

**Comment by dlombardo** [comment]
I am using the same configuration on my Linux box and Mac, yet on Linux it is not working:

`javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at /usr/local/bin/eslint
    - config file: missing`

My `.eslintrc` is located in my home directory.
I am also using `exec-path-from-shell` already (on both systems)

**Comment by cpitclaudel** [comment]
Looks like Flycheck isn't finding your .eslintrc when you're on GNU/Linux. Is it finding it on Mac? In which path?

**Comment by dlombardo** [comment]
On both systems it is located at `~/.eslintrc`

**Comment by dlombardo** [comment]
I seem to have found the problem. I had only just set up ESLint/flycheck on my Linux box the other day (it has been on my Mac for a while since that is my main work computer), and simply installed the latest `eslint` using `npm install -g` as I had before. This was a 4.0 version, which I guess is incompatible with certain configuration options such as `ecmaFeatures`. I downgraded it to `3.19.0` and it seems to be working now

Thanks for the quick response in any case

**Comment by cpitclaudel** [comment]
Thanks for the update!

**Comment by CodyReichert** [comment]
Just to expand on @dlombardo - try running eslint from your command line to make sure you don't have any errors. If you do, then that's probably the issue :)

**Comment by ldimi** [comment]
I have the same problem :  eslint config file missing.
This happens when I start emacs (27.1) by .desktop file and snap. (but eslint in M- x shell works ..)
However, when I start emacs on the commandline , everything works perfectly. Somewhere a path gets set differently, but I am unable to figure it out.

**Comment by deepanshu44** [comment]
Same issue here in linux ubuntu 20. [error-image](https://raw.githubusercontent.com/deepanshu44/emacs-flycheck-issue/master/error-display/Screenshot%20from%202021-07-04%2000-26-41.png)
tried everything but can't seem to resolve the problem.
`whereis eslint ` shows two paths now and I copied .eslintrc,json on the global path (/usr/local/bin/) as well
[This](https://github.com/deepanshu44/emacs-flycheck-issue) is my minimum working setup if devs can make it work.

Running `eslint file.js` and `npx eslint file.js` correctly identify error on 
emacs shell and terminal-
`2:11  error  Parsing error: Unexpected token test
✖ 1 problem (1 error, 0 warnings)
`

I can't find any other solution for eslint in emacs and it seems I need to switch to lsp-mode 
and drop my setup till this problem gets resolved hopefully

**Comment by AndreSeiffertSap** [comment]
I also had the problem that flycheck said "config file: missing". I can only recommend to wrap your eslint executable in a script that logs the input parameters and response from eslint into a file. You can then inspect the log file after invoking eslint via flycheck/emacs. I came up with a script like this:


```bash
#!/bin/bash

timestamp=$(date "+%Y%m%d_%H%M%S").$(python3 -c "import time; print(int((time.time() % 1)*1000))")
logfile="$HOME/${timestamp}-log.txt"

# extra parameters that eslint may need for your project setup go here
extra_params="--resolve-plugins-relative-to /some/directory"

# build the complete command to run eslint and log it
command='/path/to/eslint $extra_params $@'
echo $(eval echo "$command") >> "$logfile"

# if your project setup requires another working directory than what flycheck uses, set it here
echo $(eval pwd) >> "$logfile"
cd /path/to/working/directory

# finally call eslint and log the output.
eval $command | tee -a  "$logfile"

exit ${PIPESTATUS[0]}
```

In my case I discovered several issues:
- flycheck does not use the parameters provided with variable flycheck-eslint-args when it tries to find the config file by calling eslint --print-config
- config file was found but invalid because my config requires parameter --resolve-plugins-relative-to /some/directory
- flycheck did not determine the project root as working dir for calling eslint.
