### ISSUE TITLE
disabling "there should be two spaces after period" warning

### ISSUE THREAD

**Issue by ninrod** [flycheck/flycheck#1212]
Hi. When I'm editing elisp code, the two spaces after period warning is not wanted. I've stumbled upon this so [question](https://www.reddit.com/r/emacs/comments/5tvqqe/disabling_flychecks_double_space_after_period/?ref=share&ref_source=link), but had no luck. 

What is the recommended way to disable this specific warning? 

setting `sentence-end-double-space` to nil does not seem to help.

thanks in advance.

**Comment by fmdkdd** [comment]
If you look at the checker definition for `emacs-lisp-checkdoc`, you will see that flycheck merely calls `checkdoc-current-buffer` from `checkdoc.el`, by running it inside an `emacs -Q --batch`.

So your dotfile is not used, and setting `sentence-end-double-space` does not help here.

In fact, there does not seem to be any way to pass extra arguments to checkdoc currently, other than setting checkdoc variables.

I believe this might be intentional on the part of Flycheck.  Checkdoc ensures you follow the recommended style for docstring in elisp.  Two spaces after a period is the default style for Emacs, and therefore all packages should follow its convention.

However, checkdoc *does* test for `sentence-end-double-space` before emitting this warning, so the authors of checkdoc at least acknowledged that it can be a matter of personal taste.

I'm leaning on wontfix in this case.  If you really want to disable the warning you can modify the emacs-lisp-checkdoc checker.  But let's see what @cpitclaudel has to say.

**Comment by marsam** [comment]
With #1199 merged, you need to remove `sentence-end-double-space` from the `flycheck-emacs-lisp-checkdoc-variables` list.

**Comment by fmdkdd** [comment]
Haha, I totally overlooked that PR. Thanks @marsam.  Are you sure about removing the variable though?  After pulling the latest master, checkdoc seems to obey the value of `sentence-end-double-space` without further action on my part.

@ninrod Updating to latest flycheck version should do it.

**Comment by ninrod** [comment]
Gentleman, thank you very much. After upgrading flycheck and deleting my elpa directory, I was able to just set `sentence-end-double-space` to nil and get rid of the warning. I think this can be closed.

**Comment by marsam** [comment]
Duh forget my comment about `flycheck-emacs-lisp-checkdoc-variables`
