### ISSUE TITLE
Make compiler flags to c/c++-gcc configurable

### ISSUE THREAD

**Issue by Apakollaps** [flycheck/flycheck#1224]
While I am aware that a non-ancient version of gcc is required, and I think it is reasonable, the reality of my current environment at work is that we do use an old gcc version. This means I have to comment out the "-fno-diagnostics-show-caret" flag every time flycheck.el is updated. This happens quite often as I use spacemacs and try keep my libraries up to date.

So this is not a bug report but a change request. Please make the flags defined in the `c/c++-gcc` checker configurable. I believe this to be a minor change, and it would make those of us unfortunate enough to live in the past able to use flycheck without modification to the flycheck.el file.

**Comment by fmdkdd** [comment]
This is a very polite request, and I'm not against proposing such flag for Flycheck.  However, instead of modifying `flycheck.el` at every update, you can copy the `c/c++-gcc` checker definition to your own configuration and make the change permanent.  Since you use Spacemacs, you can put the definition in `user-config`.  If you keep the same checker name, you will override the one from `flycheck.el`, even if you upgrade.  The only downside of this method is having to manually backport any changes to the `c/c++-gcc` checker to your own version.  But that doesn't happen often.

Would that be acceptable for you?

**Comment by Apakollaps** [comment]
I know that this is another way of doing it, but the you will miss out on updates to this function... It's probably a better solution in the short run anyhow. But, another reason why I posted this jira is that we are several people at at the office that are using spacemacs, and it would be good to have a simpler solution and more official solution.

**Comment by fmdkdd** [comment]
@Apakollaps I hear you.  I will see if we can make these flags optional without too much complexity overhead (as they may impact parsing).
