### ISSUE TITLE
Get errors by checking another file

### ISSUE THREAD

**Issue by altschuler** [flycheck/flycheck#1245]
I'm using flycheck to lint template files, but the errors are reported by checking another file. Eg. `foo.html` has some errors, but they are reported by the checkter (tslint) by checking the sibling file `foo.ts`.

Is there a way to tell flycheck this:

1. When opening `<name>.html` file check if there is a sibling file `<name>.ts`
2. If yes, check the `.ts` file in addition to the `.html` and report both checker's output in the `.html` buffer.

Thank you very much for an amazing project! :)

**Comment by cpitclaudel** [comment]
No, not currently — at least not if I understand you correctly.  Shouldn't ts lint do that automatically ?

**Comment by altschuler** [comment]
I guess it could, but it makes sense that it doesn't, because the template file is dependent on the ts file, which is its context against which it's linted.

**Comment by cpitclaudel** [comment]
Sorry, in that case I don't understand. I'm not familiar with tslint; can you maybe give a bit more context?

**Comment by altschuler** [comment]
Sure! So it works like this:

tslint is the general lint tool for typescript. It supports plugins/extensions and one of these is [codelyzer](https://github.com/mgechev/codelyzer), which lints angular 2 specific things. In angular 2 you often have your templates (HTML markup) and typescript (logic/controller) split in two files. The codelyzer plugin checks whether your template has errors, eg. access to non-existing variable. The thing is, that (for instance) these variables are defined in the typescript file, so the linting of the template file is done "via" the typescript file. And that kind of makes sense because you can also inline your template in the typescript code if you want.

I'm not sure if that any less confusing...

**Comment by Simplify** [comment]
Hi @altschuler, 

`tslint` in Flycheck can lint only one file at the time and it's not aware of the other files. 

You can try [tslint-language-service](https://github.com/angelozerr/tslint-language-service) and use [tide](https://github.com/ananthakumaran/tide) in Emacs. `tslint-language-service` is "project" aware and should provide all `tslint` errors/warnings to `tsserver` and those will be merged with `tsc` errors/warnings that you get from `tide`. I didn't test it, but if it works with VSCode, Eclipse and Sublime that get errors/warnings from `tsserver`, with `tide` should work too. In that case you can disable `tslint` checker in Flycheck, because Flycheck will show `tslint` data provided by `tide`.

Let me know if this works, I'm curious :)

**Comment by altschuler** [comment]
@Simplify Interesting! I gave it a try, but couldn't get the `tslint-language-service` to kick in at all. I might try again at some point, but no luck first time around :) Thanks for sharing!

**Comment by fmdkdd** [comment]
I'm closing as `wontfix`, since project-wide errors are currently out of scope for Flycheck, and we already have #966.   I'm open to coureageous patches though ;)
