### ISSUE TITLE
Wrong type argument: flycheck-error-p

### ISSUE THREAD

**Issue by bogus34** [flycheck/flycheck#1283]
Hello!
I'm not sure if there is an error in latest flycheck or in flycheck-tide, but still.
After upgrading elpa packages today I start to get this error when checking typescript source:

`
Error from syntax checker typescript-tide: Wrong type argument: flycheck-error-p, [cl-struct-flycheck-error #<buffer index.d.ts> typescript-tide "<...>" 5 13 "Cannot find namespace 'dispatcher'." error 2503]
`

Currently I work this around by completely disabling `flycheck-assert-error-list-p` though this is obviously wrong way.

**Comment by fmdkdd** [comment]
It might be related to #1249: we added a new optional field to the `flycheck-error` struct.  Since it's optional, it shouldn't impact `typescript-tide` since it looks like they are using the `flycheck-error-new-at` constructor anyway.

Can you report your exact flycheck version (C-c ! v) and flycheck-tide version?  I'll see if I can reproduce.

**Comment by bogus34** [comment]
Flycheck version: 31snapshot (package: 20170715.1345)
tide Version: 20170712.638

Btw, just found that with my so-called-workaround `flycheck-next-error` doesn't find any errors even if they are highlighted and described on cursor/mouse over.

Thanks!

**Comment by fmdkdd** [comment]
Thanks.  I can't seem to reproduce on my side.

It might be that, because of the new field, you have some byte-compiled `.elc` files lying around with the old struct.  Could try to trash your `flycheck` and `tide` folders in `.emacs.d/elpa`, reinstall them, and try again?  

I'm sorry for any inconvenience if that is indeed the issue.  Let's hope this resurrects `flycheck-next-error` as well.

**Comment by bogus34** [comment]
You are right, it helps!
Many thanks!
