### ISSUE TITLE
[Question] In-project executables / gradle/gradlew

### ISSUE THREAD

**Issue by jojojames** [flycheck/flycheck#1382]
It looks like flycheck looks for an executable before allowing/disallowing a flycheck checker to run.

I'm trying to write a gradle extension with flycheck that leverages the project-specific gradlew (gradle wrapper). Since this wouldn't be searchable through executable-find (since it's project specific and not on the path), I'm wondering what's a good approach to 'passing' the flycheck verification and/or a clean way to make this flow work?

Right now, I've advised a few functions to allow the gradle checker to run.

https://github.com/jojojames/flycheck-gradle/blob/master/flycheck-gradle.el

**Comment by fmdkdd** [comment]
You can customize the function Flycheck uses to find executables: `flycheck-executable-find`.

**Comment by jojojames** [comment]
Isn't that a user-level defcustom. I'm not sure how to apply that in the context of a package.

**Comment by cpitclaudel** [comment]
I think the usual way to do this is to set flycheck-gradle-executable appropriately when the file is opened, so that the checker's executable variable holds an absolute path pointing to the appropriate checker.  See https://stackoverflow.com/questions/31443527/how-can-i-make-flycheck-use-virtualenv for a related example

**Comment by jojojames** [comment]
Thanks @cpitclaudel. Works for me.
