### ISSUE TITLE
error-filter is not a function

### ISSUE THREAD

**Issue by rahulvasist** [flycheck/flycheck#1398]
I'm using Spacemacs and I have a custom checker script based off of clang-checker. When Spacemacs loads, I get this error:

```
(Spacemacs) Error in dotspacemacs/user-config: :error-filter (function (lambda (errors) (let ((errors (flycheck-sanitize-errors errors))) (let ((--dolist-tail-- errors) err) (while --dolist-tail-- (setq err (car --dolist-tail--)) (let* ((v err)) (\(setf\ flycheck-error-message\) (or (flycheck-error-message err) "no message") v)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (flycheck-fold-include-levels errors "In file included from")))) of syntax checker myscript is not a function
```

This is my Spacemacs user-config code:
```
(defun dotspacemacs/user-config ()
  (with-eval-after-load "flycheck"
    (flycheck-define-checker myscript
      :command ("myscript" source-original)
      :standard-input t
      :error-patterns
      ((error line-start
              (message "In file included from") " " (or "<stdin>" (file-name))
              ":" line ":" line-end)
       (info line-start (or "<stdin>" (file-name)) ":" line ":" column
             ": note: " (optional (message)) line-end)
       (warning line-start (or "<stdin>" (file-name)) ":" line ":" column
                ": warning: " (optional (message)) line-end)
       (error line-start (or "<stdin>" (file-name)) ":" line ":" column
              ": " (or "fatal error" "error") ": " (optional (message)) line-end))
      :error-filter
      (lambda (errors)
        (let ((errors (flycheck-sanitize-errors errors)))
          (dolist (err errors)
            ;; Clang will output empty messages for #error/#warning pragmas without
            ;; messages.  We fill these empty errors with a dummy message to get
            ;; them past our error filtering
            (setf (flycheck-error-message err)
                  (or (flycheck-error-message err) "no message")))
          (flycheck-fold-include-levels errors "In file included from")))
      :modes c++-mode))
  )
```
I have also tried replacing `with-eval-after-load` with
```
(use-package flycheck
    :config
   (flycheck-define-checker myscript <...>)   
)
```
but I still see the error.

When I execute the expression manually after Spacemacs has loaded, I do not see the error.

**Comment by cpitclaudel** [comment]
You're missing the docstring in the call to flycheck-define-checker; could that be the issue?

**Comment by rahulvasist** [comment]
@cpitclaudel  I don't think so. I added the docstring:
```
    (flycheck-define-checker myscript
      "A TACC syntax checker using Clang. See URL `http://clang.llvm.org/'."
      :command ("myscript" source-original)
```
but I still get the error.

**Comment by fmdkdd** [comment]
Can reproduce with vanilla Emacs in a `with-eval-after-load`.

One way to make it work is to macro-expand the checker definition.  Probably a weird interaction between `eval-after-load` and macros.

Another solution is to byte-compile your init file and load it.

**Comment by rahulvasist** [comment]
@fmdkdd I'm not an elisp expert. Can you give some details as to how to macro-expand the definition?

**Comment by fmdkdd** [comment]
@rahulvasist Sorry.  Put your cursor on the first parenthesis of `flycheck-define-checker` and call `M-x emacs-lisp-macroexpand`.  That should replace the macro call with its expansion.

See https://www.gnu.org/software/emacs/manual/html_node/elisp/Expansion.html

Although, after re-reading the Macro chapter of the manual, I'm still not sure what's happening exactly.

**Comment by cpitclaudel** [comment]
Thanks for the investigation.  I think the problem boils down to quoting a lambda, which is usually frowned upon.

I rewrote your example as this for clarity:

```elisp
(progn
  (defmacro m (f)
    `(function ,f))
  (functionp (m (lambda ()))))
```

and then as this:

```elisp
(progn
  (defmacro m8 (f)
    `(function ,f))
  (let ((out (m8 (lambda ()))))
    (message "%s %S"
             (if (functionp out) "OK" "NOK")
             out)))
```

This produces `NOK #'(lambda nil)` on the first execution and `OK (lambda nil)` on subsequent ones.  I think it'd be worth asking emacs-devel about this.

If I change the `(lambda ())` an existing function like `1+` then everything works fine.
What might work is to check if the argument is a symbol, and only quote it in that case.  This would support both quoted and unquoted arguments.

We could even chose to only allow quoted arguments: after a while (say, a year) we'd start issuing warnings for unquoted arguments, and after one more year we'd remove the quoting code altogether.

**Comment by fmdkdd** [comment]
>  I think it'd be worth asking emacs-devel about this.

Be my guest :)

> quoting a lambda, which is usually frowned upon.

Any reference on that?  All I can find in the manual is [this](https://www.gnu.org/software/emacs/manual/html_node/elisp/Anonymous-Functions.html#Anonymous-Functions):

> The following forms are all equivalent:

     (lambda (x) (* x x))
     (function (lambda (x) (* x x)))
     #'(lambda (x) (* x x))

Which indicates that either the manual is wrong, or this is a bug, because as we have shown, these forms do not behave the same depending on what's around them.

> What might work is to check if the argument is a symbol, and only quote it in that case. This would support both quoted and unquoted arguments.

Indeed, I will try that.

> We could even chose to only allow quoted arguments: after a while (say, a year) we'd start issuing warnings for unquoted arguments, and after one more year we'd remove the quoting code altogether.

I like that plan 👍.

**Comment by cpitclaudel** [comment]
> Be my guest :)

Done

**Comment by cpitclaudel** [comment]
Long story short: this was never supposed to work :/

A bit longer: The contents of with-eval-after-load are macro-expanded before the corresponding package is loaded.  That also happens to the (quoted!) contents of eval-after-load, since a change in 2013.

So in general, it isn't safe to call a macro defined by package `foo` in a `(with-eval-after-load 'foo …)` form.  We might be able to make it work for this specific case by ensuring that we support raw and macroexpanded lambdas.

**Comment by fmdkdd** [comment]
[emacs-devel thread](https://lists.gnu.org/archive/html/emacs-devel/2018-02/msg00516.html) for posterity.

What I got from there: the minimal example is somewhat of a red herring, and related to the way `C-M-x` does its macro-expansion (which is apparently not the same thing as what Emacs does when it loads your init file *\*shrug\**).

> The contents of with-eval-after-load are macro-expanded before the corresponding package is loaded

At first I didn't understand why it wouldn't result in a straightforward `Error: 'flycheck-define-checker' is not a function`?  But apparently, macro-expansion just leaves unknown symbols alone.  So
```emacs-lisp
(with-eval-after-load 'test-macro
   (let ((out (mmm (lambda ()))))
     (message ("with-eval-after-load: %S" out))))
```
is expanded (with `macroexpand-all`) into:
```emacs-lisp
(eval-after-load (quote test-macro)
  (function (lambda nil
              (let ((out (mmm (function (lambda nil)))))
                (message ("with-eval-after-load: %S" out))))))
```
So the problem is that the `lambda` passed to `mmm` is expanded (to a function-quoted version of itself) before `mmm` gets the chance to treat these arguments.

I guess macro-expanding under unknown symbols is reasonable, under the assumptions that all macros are defined beforehand.  In the case of `eval-after-load`, it's really counter-intuitive since it breaks the simple semantics of "do exactly that after that feature has loaded".

The solution brought in the thread of requiring the feature with `eval-when-compile` defeats the purpose of `with-eval-after-load`, because it means `flycheck` is loaded unconditionally if you put that in your init file.  (Unless you *compile* your init file, but somehow that's frowned upon, and people seldom do that).

>  We might be able to make it work for this specific case by ensuring that we support raw and macroexpanded lambdas.

As I understand the issue, using `flycheck-define-checker` with `lambda` properties in `with-eval-after-load` never worked as intended, right?  It should only work in the following circumstances:
- For emacs versions before the change to `eval-after-load` somewhere in 2013
- For files where `flycheck` ends up required before `with-eval-after-load` is macro-expanded (e.g., byte-compilation with `(eval-when-compile)`).

That is to say, the only instances of raw lambdas we should encounter are in `flycheck.el`, but we can directly change all these instances instead?

**Comment by jjlee** [comment]
@cpitclaudel I've fruitlessly tried every workaround I could find mentioned in this issue.  I always get the same error about error-filter "is not a function".  Any hints?

The reason I'm doing that is to replace the `python-flake8` checker with the one from the commit before 8270309e, because I want to override `flake8` with my own command that checks the path, in order to pick an appropriate `flycheck` command that uses an appropriate version of python. I don't know how to do that with the new flake8 checker (there are reasons I don't want to *have* to tell emacs which python version a file uses, except for the purpose of which flake8 to run).

Right now I have to hack the flycheck source code :-(

I guess you have reasons for not exposing a function in addition to/instead of the macro, but maybe whatever those reasons are, it wouldn't be as bad as the status quo?

**Comment by cpitclaudel** [comment]
>  I've fruitlessly tried every workaround I could find mentioned in this issue. I always get the same error about error-filter "is not a function". Any hints?

Can you show the code at issue?

> I guess you have reasons for not exposing a function in addition to/instead of the macro,

I think I may be misunderstanding something.  Isn't `flycheck-define-command-checker` that function?

**Comment by cpitclaudel** [comment]
Moving everything to define-command-checker might be the right way to go in the long run, but in the meantime this problem exists and can be very confusing for users.

We have #1440 to solve it (maybe only partly?).  The fix for users is to either wrap the whole call to `define-checker` in `eval`, like this: `(eval '(flycheck-define-checker …))`, or to `(require 'flycheck)` before making definitions.

We can enforce the second one by autoloading `flycheck-define-checker`.
