### ISSUE TITLE
enhancement request: allow customizing font faces in flycheck list

### ISSUE THREAD

**Issue by mattsawyer77** [flycheck/flycheck#1493]
I was hoping to be able to customize the font faces in the error list, so that I could use a smaller (and perhaps different) font. But after customizing all the error list faces I could find, there were a few parts of the list that do not seem to be styled using a flycheck face. 

I would hope that 
A) there is a face from which all our faces in the list inherit, and/or 
B) there is a face that correlates to each part of the error list

**Comment by cpitclaudel** [comment]
Sorry; it seems that this issue just flew under the radar.  Both changes that you propose are reasonable, starting with a common parent face.  Is it something you would be interested in working on?

**Comment by mattsawyer77** [comment]
@cpitclaudel I wish I had the elisp skills (and time) to make this happen. if no one else takes it I might look into it eventually.

**Comment by cpitclaudel** [comment]
That would be great.  I think it wouldn't be too hard.  I can help if you have any questions.  We could faces for the missing parts, (look for `(defface flycheck-error-list-`), or we can just add a shared parent to all of them.    I think I prefer the first option, since we have many faces for the error list already, but in fact implementing both might be the ideal approach.
