### ISSUE TITLE
flycheck cannot find file in cached bazel output folder

### ISSUE THREAD

**Issue by shelper** [flycheck/flycheck#1558]
So i have flycheck installed and works great with common projects.
but i have a project that uses bazel and i have the compilation_commands.json in the root directory, and flycheck gives  lots of errors about `cannot find files`
here is what happend: i have 
- project root at `/a/b/c/` that has compilation_commands.json which has, for example, one command as:
```
    {
        "directory": "/a/b/c/src",
        "command": "bazel/tools/cpp/wrappers/clang ...  bazel-out/.../some_output_file x
        ...
    }
```
here `bazel-out` folder is in `/a/b/c/src/`.

now if i open a source file at `/a/b/c/src/sub_folder/foo.cc`, then flychecker complains that it cannot find `bazel-out/.../some_outputfile`, but if i move `foo.cc` to `/a/b/c/src/`, then that specific error is gone.
I tried to add `/a/b/c/src/` to the include path list of flycheck but seems no help.

my understanding is that my building tool (not setup by me but the developer-tools team) loads the external packages from remote and have a local cache for it, which is located in `bazel-out/...`. in such case flycheck cannot find files from cache and thus generate a lot of errors. 

configuring `flycheck-clang-include-path` by adding `/a/b/c/src/` does not help ...
not sure if i explained clearly, hope i can get some help here....
thanks!
![image](https://user-images.githubusercontent.com/546163/55294987-4fe49d00-53d6-11e9-9374-a5746787728d.png)

**Comment by fmdkdd** [comment]
I'm not I understood your scenario.  I'll try to reword it—correct me if I'm wrong:

- You are using `flycheck-clang` to flycheck C++ files
- Your C++ project is built using bazel
- The project is configured so that bazel fetches additional headers, which are necessary for building
- `flycheck-clang` cannot find these additional headers, so you get a bunch of spurious errors when editing files under Emacs
- Adding the folder of these additional headers to `flycheck-clang-include-path` does not help

First thing would be to ensure that `clang` can detect those files.  If you run `M-x flycheck-compile c/c++-clang RET` in a buffer, it should give you the command that `flycheck-clang` executes on your files (including the value for `flycheck-clang-include-path`).  Try to run that command on the command line, in the directory of the file you want to check.  Does clang report `cannot find files` errors there?

**Comment by shelper** [comment]
`clang -fsyntax-only -fno-color-diagnostics -fno-caret-diagnostics -fno-diagnostics-show-option -iquote /home/user/workspace/source/estimation/ -Wall -Wextra -I /home/user/workspace/source/ -x c\+\+ - < /home/user/workspace/source/estimation/pnp.cc
In file included from <stdin>:5:
In file included from /home/user/workspace/source/estimation/pnp.hh:7:
In file included from /home/user/workspace/source/model/model.hh:7:
/home/user/workspace/source/libs/geometry/vector.hh:7:10: fatal error: 'Eigen/Core' file not found
`

**Comment by shelper** [comment]
i believe this is the reason 
quoted from https://nilsdeppe.com/posts/emacs-c++-ide

>  Flycheck seems to parse the code local to the buffer, and so if that code does not compile stand-alone then you get strange errors. This could be seen as a good thing since it will force developers to explicitly include headers they use rather than using functions or classes because they are included in a header file that’s being included. So the lesson here is that if you get strange errors, don’t look at the first error, look at all of them and see if it could be related to missing headers preventing Flycheck from analyzing the code locally.

**Comment by fmdkdd** [comment]
The only thing that Flycheck does is "execute clang on the current file, collect the errors, show them to the user".  The tricky part is matching the way clang is invoked by your build tool to the way Flycheck invokes clang.  In my C projects, I usually solve the problem by setting `flycheck-clang-include-path` in a .dir-locals.el file for each subdirectory that needs to access external dependencies.  In large projects it may be a more difficult proposition. 

Keep in mind that if you have a build tool that produces errors on the command line, you can also write a Flycheck checker directly for it.  Usually you don't want to run full builds to get diagnostic feedback faster, so if your build tool has an option for "checking only" this is even better.

Otherwise I believe [flycheck-irony](https://github.com/Sarcasm/flycheck-irony) is made for helping discovering configuration.

**Comment by shelper** [comment]
i tried flycheck-irony, and it is the same error

anyway thanks for explaination, that helps！

**Comment by fmdkdd** [comment]
You are welcome.  If you do find a solution to your situation, do keep us posted as it can help others who are in the same situation.

In the meantime, I'll close this since we already have options for configuration, and using Flycheck for large projects is probably out of scope without the help of exterior plugins.
