### ISSUE TITLE
Flycheck cannot open load file: No such file or directory

### ISSUE THREAD

**Issue by c4dr01d** [flycheck/flycheck#1559]
Hello, I'm configuring my emacs using emacs lisp, when I configured flycheck and installed, I opened ~/.emacs.d/init.el, The flycheck display a error at line 20, error say:
Cannot open load file: No such file or directory, init-utils
My emacs configuration link: [Emacs configuration](https://github.com/c4dr01d/.emacs.d)

**Comment by c4dr01d** [comment]
The file actually exists at load-path, why flycheck still check it as a error?

**Comment by c4dr01d** [comment]
Now emacs generate a error when I start it everytime

**Comment by fmdkdd** [comment]
It seems you are saying that Flycheck cannot find some of your init files when trying to check your main init file, even though Emacs is able to find them (because they are in `load-path`).  If that's the case, you probably want to `(setq flycheck-emacs-lisp-load-path 'inherit)` [see the docstring](https://github.com/flycheck/flycheck/blob/9cd52ad65b4cc643b9e6ba7cefb8d82777da2a13/flycheck.el#L7338).

**Comment by c4dr01d** [comment]
OK，I will try it.

**Comment by mrcnski** [comment]
> If that's the case, you probably want to (setq flycheck-emacs-lisp-load-path 'inherit)

Thanks! But it really makes me wonder why this isn't the default value. I wasted a lot of time because I thought it was an issue with my config, not realizing this was a flycheck bug. :/ Perhaps the error message could at least hint at this option...
