### ISSUE TITLE
Developer and contributor documentation

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#323]
Write a good and comprehensive developer documentation, which includes at least

**Comment by CyberShadow** [comment]
Where can I find information on how to add FlyCheck support for a language?

The website has a "The Developer Guide" section, but all it says is "Todo: Port the extending section from the Texinfo manual".

Okay, where's the texinfo manual? No link is provided.

I found a `flycheck-info` function, but all it does is open the same website.

I search online for "flycheck developer", nothing relevant.

I search online for "flycheck texinfo", and find this:

https://github.com/flycheck/flycheck/issues/924

From there, I see that that issue is mentioned here:

https://github.com/dimitri/el-get/pull/2356

From there, I see a path mentioned in an error message:

```
doc/legacy/flycheck.texi:64: @pxref reference to nonexistent node `Installation'
```

Okay, so I go back to FlyCheck's repo and find `doc/legacy/flycheck.html`. I paste that into rawgit.com to get:

https://raw.githubusercontent.com/flycheck/flycheck/master/doc/legacy/flycheck.html

And that page finally has some information on the subject.

Surely there's gotta be a simpler way!

**Comment by lunaryorn** [comment]
@CyberShadow 

> Okay, where's the texinfo manual? No link is provided.

There's a link in the [User Guide](http://www.flycheck.org/en/latest/#the-user-guide) but it's arguably not very prominent.  If you can suggest a better way to reference it please let's hear it :blush:

> Surely there's gotta be a simpler way!

Indeed, and that's what this issue is for.  But documentation takes time to write, and if you take a look at [our board](https://waffle.io/flycheck/flycheck) you'll see that there's *a lot* to do.

However, there's already a simpler way that what you did:  **Ask Emacs!**  If you take a look at the documentation of syntax checkers with `C-c ! ?` you'll see that the Help buffer provides a link to the source of the corresponding syntax checker, and all of our built-in syntax checkers are perfect examples for extending Flycheck with new syntax checkers.

From the source code of a syntax checker you can browse the docstrings of Flycheck's functions with `C-h f`, which will lead you to the docstrings of `flycheck-define-checker`, `flycheck-define-command-checker`, and friends, which—albeit indirectly—provide a reference of all properties of syntax checkers and their meanings.

**Comment by CyberShadow** [comment]
> However, there's already a simpler way that what you did: Ask Emacs!

Thanks for replying, and this is what I did in the end for the nitty-gritty (my end result is [here](https://github.com/CyberShadow/hrm-mode/blob/master/hrm-mode-flycheck.el)). I just didn't know where to start looking, so since there was an official manual that was my starting point. 

Another thing that really helped is this excellent blog post:

http://www.lunaryorn.com/2014/12/03/generic-syntax-checkers-in-flycheck.html

The last bit that left me scratching my head for 15 minutes was that I had to register my checker by adding it to `flycheck-checkers`, I thought `flycheck-define-generic-checker` would do that for me. Neither the blog post, `flycheck-define-generic-checker` documentation, or the examples in `flycheck.el` did that (around the place in the code where they were defined), though to my discredit it is mentioned very prominently in the TexInfo manual, so this is probably a PEBCAK.

> There's a link in the User Guide but it's arguably not very prominent. If you can suggest a better way to reference it please let's hear it :blush:

Thanks, I did miss that (I had no issues with *using* FlyCheck, so I jumped straight to the "Developer Guide" section). Perhaps the TODO blocks could link to it?

**Comment by lunaryorn** [comment]
@CyberShadow  I'll try my best to finish the manual as soon as possible.  Please subscribe to #928 to follow the progress of the developer documentation.

> The last bit that left me scratching my head for 15 minutes was that I had to register my checker by adding it to flycheck-checkers, I thought flycheck-define-generic-checker would do that for me. Neither the blog post, flycheck-define-generic-checker documentation, or the examples in flycheck.el did that (around the place in the code where they were defined).

Oh, I must admit that this comes as a surprise, for `flycheck-checkers` is actually mentioned in the very first paragraph of the docstring of `flycheck-define-generic-checker`, right after the summary line:

> Any syntax checker defined with this macro is eligible for manual
syntax checker selection with `flycheck-select-checker'.  **To make
the new syntax checker available for automatic selection, it must
be registered in `flycheck-checkers'.**

How can we improve the documentation so that it's less unclear here?

> Thanks, I did miss that (I had no issues with using FlyCheck, so I jumped straight to the "Developer Guide" section). Perhaps the TODO blocks could link to it?

That's a good idea; I've pushed a corresponding change which should appear in the online manual shortly.

**Comment by CyberShadow** [comment]
> Oh, I must admit that this comes as a surprise

I bow my head in shame. PEBCAK indeed.

Thanks again!
