### ISSUE TITLE
Flycheck Auto Generating File on Save

### ISSUE THREAD

**Issue by nayefc** [flycheck/flycheck#334]
I am using flake8 for python files. Whenever I save a file, flycheck generates a new file called: `flycheck_nameOfFile.py`. This did not happen with pylint. I looked at flake8 and pyflakes, and they don't seem to be generating any reports. I am suspecting this is form flycheck since the new file name is preceded with flycheck.

Is there a way to disable this behaviour?

**Comment by rgkirch** [comment]
I ended up editing the "flycheck_*" version of the file without noticing. A while later, I noticed the "flycheck-*" file and didn't know what it was so I deleted it. Now I feel sad because I just deleted what I've been working on. I would like a way to disable this or use `/tmp` as a directory for the file.
:cry:

**Comment by rgkirch** [comment]
Flycheck version: 35.0-snapshot

**Comment by rgkirch** [comment]
Crap. It turns out, the way I deleted it in emacs sent it to the trash. I found it in the trash and clicked "restore" and now it's really gone. Crap. I wonder if flycheck deleted it after it got restored. Crap.

**Comment by rgkirch** [comment]
Umm. I found it running `find . flycheck_config.el` and opened it in emacs and copied the contents. It doesn't show up in dired though. It's also definitely gone now even though I didn't delete it.
