### ISSUE TITLE
Add checkdoc checker.

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#53]
Add checker for Emacs Lisp calling `(checkdoc-current-buffer t)`  in an Emacs subprocess.

Use checker chaining #31 to call this checker after the standard Emacs Lisp.

**Comment by cpitclaudel** [comment]
@lunaryorn, I was looking at this and wondering: have we ever considered support for file-local variables as a way to handle this problem? This would be similar to how some checkers allow you to configure the warnings for a file by adding special comments (and I would consider it good practice to make such settings parts of a file, so that everyone in a project checks the file according to the same standards)
