### ISSUE TITLE
Flycheck in Tramp freezes Emacs

### ISSUE THREAD

**Issue by msimav** [flycheck/flycheck#54]
When editing a file over ssh with tramp, emacs stops responsing and wont work before kiling ssh process under emacs.

I think it tries to run syntax checker on remote which is not installed.

**Comment by root42** [comment]
Tramp support would be a great idea for things like C/C++ coding. My workstation is a MacBook, however I am working on a large Linux based C/C++ project. I edit the files with the OS X native Emacs via Tramp. This works all very fine, I can even use ggtags to navigate the remote project using the remote GNU global. I am now determining how I can get flycheck and company to work like this as well. Important thing here is that I am able to set the clang arguments accordingly to fill up the include paths etc. This is also necessary for the company-clang backend, and depends on the user's project, hence should be configurable.

If I manage to get start-file-process to behave correctly, I think we might have a solution. I will report back when I find the time to work on this problem and have some results.

In general I would assume that for a remote file, flycheck should always run the check on the remote machine -- or not at all if the user wishes to disable flycheck on remote buffers. The use case here being that Emacs is being used to edit a remote project, instead of tunneling Emacs via X11+ssh or something like that.
