### ISSUE TITLE
Flycheck doesn't pick-up the custom checker when started

### ISSUE THREAD

**Issue by Sarcasm** [flycheck/flycheck#559]
Hi,

I'm the author of a custom flycheck checker https://github.com/Sarcasm/flycheck-irony. To initialize my checker I use the following lines (see [README.md#Configuration](https://github.com/Sarcasm/flycheck-irony#configuration)):

```el
(eval-after-load 'flycheck
  '(add-to-list 'flycheck-checkers 'irony))
```

The thing is that my custom checker isn't picked up by default on every buffer I open. Instead the `c/c++-clang` checker is used.

If I restart flycheck (calling `M-x flycheck-mode RET` twice), then irony is picked up.

I guess this might be due to the order of initialization between flycheck and irony (I realized just now, while writing this issue, that this is probably the root of the problem).

How do you deal with that without requiring each user to be careful about the initialization order?

Also it looks like that `flycheck-select-checker` doesn't work if I call select `irony`. It looks like the `:predicate` that `flycheck-irony` sets isn't checked again. If a checker cannot be selected for this reason maybe it will be better not to provided it in `flycheck-select-checker` completion list.

**Comment by lunaryorn** [comment]
@Sarcasm It's likely an initialization issue, but it's a strange one, since Flycheck actually tries to avoid early syntax checks.  How does your initialization look like?

> So it looks like that flycheck-select-checker doesn't work if I call select irony. It looks like the :predicate that flycheck-irony sets isn't checked again. 

It is.  Whatever the issue is, it has another cause, but “doesn't work” is hardly a sufficient description to explain the problem.

**Comment by Sarcasm** [comment]
> How does your initialization look like?

Something like that:

```el
;; init-flycheck.el
(add-hook 'after-init-hook #'global-flycheck-mode)

;; init-irony.el
(add-hook 'c++-mode-hook 'irony-mode)

;; init-flycheck-irony.el
(require 'flycheck-irony)
(eval-after-load 'flycheck
  '(add-to-list 'flycheck-checkers 'irony))
```

> It is. Whatever the issue is, it has another cause, but “doesn't work” is hardly a sufficient description to explain the problem.

Well sometimes the `*Flycheck errors*` buffer is still showing up the old checker. I tried to find the way to reproduce it but I can't, so I guess you can ignore this maybe that was just the new syntax check taking time.

**Comment by lunaryorn** [comment]
@Sarcasm “Like that”?  Now, is that your initialization, or not?  

With that code, Flycheck shouldn't check the buffer before `irony-mode` is activated.  Flycheck actively defers the first syntax check until after the window configuration changed or the current command finished, precisely to avoid any dependencies on minor mode initialization order.  

By the time the new buffer becomes current or the command that created the buffer has finished, C++ Mode is completely set up, which means it has run its hooks and enabled all minor modes therein.

IOW, with that setup Flycheck won't check the buffer until Irony Mode is enabled and the `:predicate` of `irony` holds.

So, do you have **any** other Flycheck related code in your init file?  Do you explicitly call `flycheck-buffer` somewhere?

**Comment by Sarcasm** [comment]
> @Sarcasm “Like that”? Now, is that your initialization, or not?

Regarding flycheck it is exactly that. For `irony` itself I have a bit more but nothing that impacts `flycheck`.

> By the time the new buffer becomes current or the command that created the buffer has finished, C++ Mode is completely set up, which means it has run its hooks and enabled all minor modes therein.

IIRC, for some reasons `c++-mode-hook` is often run twice in a row, so does irony-mode in this case, can this be a problem?

> So, do you have any other Flycheck related code in your init file? Do you explicitly call flycheck-buffer somewhere?

No and no.

**Comment by Sarcasm** [comment]
I tweaked my `:predicate` to show whether or not `irony-mode` is enabled when checked:

```el
  :predicate #'(lambda ()
                 (message "is irony-mode enabled for %s? %s" buffer-file-name irony-mode)
                 irony-mode))
```

It shows that `irony-mode` wasn't enabled when first called:

    is irony-mode enabled for /home/gpapin/projects/foo/main.cpp? nil

**Comment by lunaryorn** [comment]
@Sarcasm I'll take a look.

**Comment by lunaryorn** [comment]
@Sarcasm I'm sorry, but I completely failed to re-produce the issue. I used [this init file](https://gist.github.com/lunaryorn/a27bd8369395acf09300), which defines a dummy syntax checker and a dummy minor mode to reflect your setup.  I didn't try with Irony Mode itself, because I was admittedly to lazy to build it, but the dummy minor mode and checker should work identically for our purposes.

When I start Emacs with `emacs -nw -Q -l init.el` and visit a C file, e.g. `test/resources/checkers/c_c++-warnings.c` from Flycheck's source code, I see the error from the dummy syntax checker.  IOW, the minor mode is enabled *before* Flycheck tries to select a syntax checker.

If I then manually disable the minor mode with `M-x foo-mode` and type `C-c ! c` to check the buffer again, the dummy syntax checker isn't used anymore, and instead I see errors from Clang.

Would you mind to try Flycheck and your Irony checker in `emacs -Q`?

**Comment by Sarcasm** [comment]
Yeah I will try, I wanted to debug the issue yesterday at home but it doesn't happen there...will keep you updated.

**Comment by lunaryorn** [comment]
@Sarcasm Thanks.

**Comment by Sarcasm** [comment]
With the following initialization I am able to reproduce the issue.

```el
;;; emacs.el --- Flycheck: Init file for testing      -*- lexical-binding: t; -*-

(add-to-list 'load-path "~/.emacs.d/elpa/dash-20141220.1452")
(add-to-list 'load-path "~/.emacs.d/elpa/flycheck-20150103.323")

(require 'flycheck)

(global-flycheck-mode 1)

;; Foo

(define-minor-mode foo-mode "A funny mode")

(flycheck-define-generic-checker 'foo
  "A foo checker."
  :start (lambda (checker callback)
           (let ((buffer (current-buffer)))
             (run-with-idle-timer
              1 nil
              (lambda ()
                (funcall callback 'finished
                         (with-current-buffer buffer
			   (list (flycheck-error-new-at 1 1 'warning "Foo"
							:checker checker))))))))
  :modes '(c-mode c++-mode)
  :predicate (lambda () foo-mode))

(add-hook 'c++-mode-hook #'foo-mode)

(eval-after-load 'flycheck
  '(add-to-list 'flycheck-checkers 'foo))
```

FYI: I have Emacs 24.3.1

Also something is weird, flycheck errors buffer shows:

```
    1   1 warning          (foo)
```

The message `Foo` is lacking but on mouse over, in the source file Foo is displayed in a tooltip correctly.

Will continue to investigate later.

**Comment by Sarcasm** [comment]
With your gist I have the same issue.

I had to comment the following:

```el
;; (let* ((source-dir (locate-dominating-file load-file-name "flycheck.el")))
;;   (load (expand-file-name "flycheck.el" source-dir)))
```

Could this be a due to the different Emacs version?

**Comment by lunaryorn** [comment]
@Sarcasm Uh, that part should be entirely unrelated.  All it does is to load Flycheck from source instead of using the one from MELPA.

I'll try with 24.3.

**Comment by lunaryorn** [comment]
@Sarcasm I could re-produce the issue in 24.3, and fixed it in master.

In 24.3 globalized minor modes are apparently applied to a buffer before major and minor mode hooks were run.  At this point, Flycheck would select a checker to determine whether it supports the current major mode, and cache the result of this selection for later use.  When Irony Mode was enabled through the major mode hook later on, it was available for selection, but Flycheck would still use the cached value from before.

24.4 seems to have changed the order in which globalized minor modes are applied, running them after all hooks.  Irony Mode was enabled before Flycheck kicked in, which is why I couldn't reproduce it in 24.4.

I changed Flycheck to only cache a selected checker if it actually uses it for a real syntax check, which delays the caching until the first check actually runs, which in turn only happens after all hooks were run, and all minor modes set up.

Please try the latest master and tell me whether the issue is fixed for you.  Thanks for reporting this issue, and for your feedback and your patience while walking through this with me.  Many thanks!

**Comment by Sarcasm** [comment]
Looks like it work, many thanks to you!

I will enjoy `flycheck` much more now! :)

**Comment by lunaryorn** [comment]
@Sarcasm You are welcome!

**Comment by chenpoyang** [comment]
using use-package to manage the packages, and the problems occur: Flycheck doesn't pick-up the custom checker when started
and i change the code to these order and it works:
<pre>
"---------------------------------------------------------------------------"
;; irony-mode
(use-package irony
  :config
  (defun my-irony-mode-on ()
    ;; avoid enabling irony-mode in modes that inherits c-mode, e.g: php-mode
    (when (member major-mode irony-supported-major-modes)
      (irony-mode 1)))

  (add-hook 'c++-mode-hook 'my-irony-mode-on)
  (add-hook 'c-mode-hook 'my-irony-mode-on)
  (add-hook 'objc-mode-hook 'my-irony-mode-on)

  (defun my-irony-mode-hook ()
    (define-key irony-mode-map [remap completion-at-point]
      'irony-completion-at-point-async)
    (define-key irony-mode-map [remap complete-symbol]
      'irony-completion-at-point-async))

  (add-hook 'irony-mode-hook 'my-irony-mode-hook)

  (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))
"---------------------------------------------------------------------------"
;; flycheck
(use-package flycheck
  :config
  (add-hook 'after-init-hook #'global-flycheck-mode)
  (setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)))

(use-package flycheck-irony
  :after (flycheck)
  :config
  (add-hook 'flycheck-mode-hook #'flycheck-irony-setup)
  (add-to-list 'flycheck-checkers 'irony)
  ;; using :bind make flycheck-irony not working
  (global-set-key (kbd "<f9>") 'global-flycheck-mode))
"---------------------------------------------------------------------------"
</pre>
:bind keyword make the package flycheck-irony load first and the bind the keys, which is conflict with :after(flycheck)
