### ISSUE TITLE
No way to re-enable checker after threshold limit is reached

### ISSUE THREAD

**Issue by jonathanj** [flycheck/flycheck#590]
When editing a moderately sized source file, in this case Python, it's trivial to introduce syntax temporarily that renders the rest of the file incomprehensible garbage to a checker like flake8. The threshold limit of 400 (the default) is quickly reached and the checker disabled for the buffer.

5 seconds later you finish typing what you started but the checker is disabled. Attempting to reenable the checker with `C-u M-x flycheck-disable-checker RET python-flake8` doesn't seem to actually reenable the checker. I'm using version 20150207.32 but I can recall it happening before this version.

Without resorting to disabling the threshold for flycheck as a whole, I would ideally like the checker to be temporarily disabled until I manually recheck the buffer (or some similar behaviour.)

Hopefully I didn't misunderstand how the threshold works or overlook how to reenable a checker.

**Comment by lunaryorn** [comment]
@jonathanj Does `M-: (setq flycheck-disabled-checkers nil)` and then `M-x flycheck-buffer` re-enable the syntax checker?

**Comment by lunaryorn** [comment]
@jonathanj Did you try these commands?

**Comment by jonathanj** [comment]
@lunaryorn, sorry about the delay in getting back to you.

I tried these commands but the flake8 checker is still not re-enabled.

**Comment by lunaryorn** [comment]
@jonathanj With the next MELPA build, re-enabling the checker with `C-u M-x flycheck-disable-checker RET python-flake8` should work properly.  It still means that the checker will temporarily stop working if there are too many errors, but you can at least properly re-enable it now.

I'm not sure whether we can reasonably fix the real issue, because Flycheck as little chance to determine whether the file is just temporarily broken because a specific error caused many “follow-ups”, or whether it's really broken with too many “real” errors.

**Comment by lunaryorn** [comment]
Closing due to the lack of activity.  I presume the issue is solved now.

**Comment by jonathanj** [comment]
@lunaryorn Sorry about the huge latency in replies. Manually being able to re-enable the checker is indeed an acceptable solution for me, thank you!

**Comment by lunaryorn** [comment]
Never mind, thanks for your feedback.  I'm happy that the issue is fixed for you!
