### ISSUE TITLE
Support for deleting option "-fno-diagnostics-show-caret" in gcc checker

### ISSUE THREAD

**Issue by YorkZ** [flycheck/flycheck#596]
First of all, thank a lot for this wonderful package, it's super promising. However, as I tried to use it on my project at work, I have a problem.

Because my project can only be compiled with GCC 4.6.3, I have to use the gcc checker, i.e., I added `(flycheck-select-checker 'c/c++-gcc)' in my .emacs. My problem is that GCC 4.6.3 doesn't support the "-fno-diagnostics-show-caret" option. But this option has been hard coded in flycheck.el:

    (flycheck-define-checker c/c++-gcc
      "A C/C++ syntax checker using GCC.
  
    Requires GCC 4.8 or newer.  See URL `https://gcc.gnu.org/'."
      :command ("gcc"
                "-fshow-column"
                "-fno-diagnostics-show-caret" ; Do not visually indicate the source location
                "-fno-diagnostics-show-option" ; Do not show the corresponding
                                               ; warning group
                "-iquote" (eval (flycheck-c/c++-quoted-include-directory))
                (option "-std=" flycheck-gcc-language-standard concat)

I've tried removing the hard coded option "-fno-diagnostics-show-caret" in the above code and it worked. Therefore, my question is: is there a way to customize this so that one doesn't have to remove the hard coded line in the source code?

**Comment by lunaryorn** [comment]
@YorkZ Why can't you use GCC 4.8?  It's just for syntax checking after all, so it shouldn't matter what compiler you need to use for real builds…

**Comment by YorkZ** [comment]
@lunaryorn: it's a very large project that complie only on GCC 4.6. Trying to compile it on GCC versions higher than 4.7 would produce numerous errors. Personally, I would love to make it compile on GCC 4.9.2. Unfortunately, I'm not the person who will make the decision. Therefore, I still hope flycheck supports GCC 4.6. I think I may be able to help with that.

**Comment by lunaryorn** [comment]
@YorkZ Again, with Flycheck you are *not* compiling the whole project.  You're just checking individual files.

Can't you prevent these errors with appropriate flags for GCC?  I have a hard time to believe that this should be altogether impossible.

That said, we deliberately decided to drop GCC 4.6 support a while ago, and I'm not particularly keen on introducing it again.

**Comment by YorkZ** [comment]
> jwith Flycheck you are not compiling the whole project. You're just checking
> individual files.

I understood it was not compiling the whole project. I understood I was just checking individual files. However, even "one file" could be non-trivial. More precisely, it's not just "one file", but a "compilation unit" that can include many many dependencies.

> Can't you prevent these errors with appropriate flags for GCC? I have a hard
> time to believe that this should be altogether impossible.

It's a very large and complex project. Again, it's not as trivial as simply using a few preprocessor tokens. If it's that simple many other developers would have done that already, and I wouldn't have bothered taking time to post issue here.

> That said, we deliberately decided to drop GCC 4.6 support a while ago, and
> I'm not particularly keen on introducing it again.

I understand that. I actually don't mind whether it's called "support GCC 4.6" or not. All I'm interested in is to not hard code "-fno-diagnostics-show-caret", if at all possible.

**Comment by lunaryorn** [comment]
@YorkZ As far as I am concerned, making `-fno-diagnostics-show-caret` optional *is* “supporting GCC 4.6”, which is not what I want.  I'm not going to make this setting customizable:  It'd be a false promise, since I might introduce other, more important GCC 4.8-only flags any time.

If your project is so large and complex that you cannot easily use GCC 4.8 with it, you are better of with your own syntax checker anyway, because your setup is inevitably so brittle that any change to the GCC flags used in Flycheck might break it.

Copy the GCC syntax checker, call it `c/c++-gcc-for-my-foo-project`, and use a `:command` that's directly tuned to your project.  That's more reliable for your use case, regardless of whether I make said option customizable or not.

**Comment by mijoharas** [comment]
On this point, how can I have a different gcc for my syntax-checker and a different gcc for my compile command?

If I understand your point correctly, you recommend having `gcc` be a gcc version `4.8` or above? if I do that I'd have to rewrite my whole teams makefiles (which they're not going to let me do) or personally modify `flycheck.el` (which is my current solution) to make it work with `gcc-4.7` (which is the version I need to use).

While I agree with your point on not wanting to support an old `gcc` is there any chance that you can allow for the command to be altered after instantiation, so that I can manually set it in my `.emacs` or whatever?

My problem is that this seems to be asking people to pick either a simple solution for flychecking or a simple solution for compilation, and compilation settings live in makefiles and can't necessarily be changed when there is a large team involved, whereas flycheck lives in my emacs distro so I can change it myself, ideally with a configuration option so I don't need to modify flycheck every time it updates.

Or alternatively, can I configure flycheck so that it looks for `gcc-4.8` to flycheck things? I'm happy for it to use `gcc-4.8`, but my `gcc` command needs to be linked to `gcc-4.7`.
