### ISSUE TITLE
" FlyC" in modeline

### ISSUE THREAD

**Issue by chillum** [flycheck/flycheck#597]
Hey,

I would like to change the `FlyC` in modeline to `Chk`. I think, it would be more clear, that's FlyCheck (I use Flyspell as well, it's `Fly`). This value is hardcoded in `flycheck-mode-line-status-text` function.

Basically, there are two options:

1. We can make the text " FlyC" to be a custom variable, so it's possible to easy change it without having to re-write the `flycheck-mode-line-status-text` function and specifying my function in `flycheck-mode-line` -- for user customization of just this text: FlyC.

2. The second option is actually to change `FlyC` to `Chk`.

My point is: `FlyC` name in modeline looks cryptic and is easily confused with `Fly` for Flyspell. I would like to change the entire modeline string, but it's you to choose.

Let's think, what way is better. If we settle on a certain opinion, I'll be able to prepare a patch. For my point simply changing the `FlyC` string with `Chk` makes sense, but I'm not sure, the authors and community will adopt it.

**Comment by lunaryorn** [comment]
@chillum I think that neither way is “better”, and I do not want to introduce another option for the mode line, which I'd have to test, maintain and support.

Please write your own status function, and customize `flycheck-mode-line` accordingly.

**Comment by chillum** [comment]
Sebastian!

Is moving to a variable the hardcoded _string_ in modeline worth a lot of testing, maintaining and supporting?

Let me explain my opinion:

I'm using Emacs for 10+ years, I have some patches merged in GNU Emacs and XEmacs cores (there was day, it was really popular) and some elisp modes.

At one day, I've lost all my emacs configs. With lots of custom functions and like this. And setting up Emacs again I've realized, that I do not want to write any custom functions. I just want to use that new `M-x customize` thing. New? It's 15 years and widely adopted.

That is: I can write elisp code. I can copy your `flycheck-mode-line-status-text` function and substitute the string. I can specify my function in the `flycheck-mode-line` variable. But for just only changing the hardcoded `FlyC` string in the modeline? It's not the Emacs way for sure.

I understand, you would like to see `FlyC` in modeline and call everyone wishing to change it a moron and/or make them to add 9 lines of elisp to their config. But what's really wrong in making the hardcoded `FlyC` string a variable?

The Emacs way is surely is extensibility. Not the extensibility like: if you want it another way, rewrite it. The extensibility is: if you want it another way, we have a user option.

If you would reconsider about this, let me know and I'll prepare a patch, moving ` FlyC` string to a variable. That would be not much hassle to you as a maintainer. :-)

**Comment by lunaryorn** [comment]
@chillum I think it's my business to assess what constitutes a “hassle” for me, and what not.  I also think that we have quite different perceptions of what is the “Emacs way”, and with regards to Flycheck I hold my perception to be more relevant than yours.  

In other words, I do *not* intend to add options for each and every minor feature of Flycheck.   For some thing, you'll just have to write your own code, because I consider them too complex, too exotic or too minor for me to support them in Flycheck—the latter being the case here.

Extensibility is that I give you *some* chance to change the behaviour you do not like.  It's not that I give you the chance that you'd like to have, specifically if it doesn't come for free for me.

But anyhow, feel free to open a pull request for a new option.  If it comes with proper docstrings, manual and unit tests, I'll probably merge it, but don't expect me to spend a lot of time on reviewing it.  It's too small a thing for me to spend any more time on this.

**Comment by chillum** [comment]
@lunaryorn I understand your concerns, thanks.

For now I've set-up a different Flyspell modeline and seem to be happy and probably will not return to this question.

You are being an author and maintainer of several really nice elisp modes, like FlyCheck and puppet-mode. I use both and am very happy.

Thanks for this discussion. Now, I've used FlyCheck for a couple of days and learned, that I can go around the mentioned customization of it. I think, I won't return to writing this patch.

FlyCheck is really a nice piece of software. You keep a great job writing and maintaining it.
