### ISSUE TITLE
Can you elaborate on this error? Warning: Bug in web-mode: it forgets to call `run-mode-hooks'

### ISSUE THREAD

**Issue by jeffbski** [flycheck/flycheck#613]
Can you elaborate on this error which I am getting when trying to use flycheck with eslint on a jsx file being edited in web-mode? Author of web-mode is trying to understand what is needed here.

```
File mode specification error: (user-error "Can't use syntax checker javascript-eslint in this buffer")
Warning: Bug in web-mode: it forgets to call `run-mode-hooks'
File mode specification error: (user-error "Can't use syntax checker javascript-eslint in this buffer")
```

I have reached out to the author of web-mode about the missing `run-mode-hooks` call, but he would like additional information about specifically what is missing. 

The issue in detail is logged here: https://github.com/fxbois/web-mode/issues/473#issuecomment-87253453

I have searched this flycheck source tree and couldn't figure out where the error was coming from myself, so hopefully you can provide some additional information about what web-mode is missing.

Thanks in advance for any help.

**Comment by lunaryorn** [comment]
@jeffbski I don't know about the `run-mode-hooks` thing, but the Flycheck error means what it says:  You can't use the eslint checker in Web Mode.  

I presume you set `flycheck-checker` or call `flycheck-select-checker` in `web-mode-hook`, overriding Flycheck's automatic selection, which would never have selected eslint checker in a Web Mode buffer.  Thus you force Flycheck to try and use this checker, which fails since the checker is not allowed in Web Mode.  In fact, no checker does—Flycheck does not support Web Mode at all.

Closing as invalid.  You can use `flycheck-add-mode` to add Web Mode to eslint, but be aware that you will get many wrong reports then for Web Mode buffers that don't contain Javascript.

**Comment by jeffbski** [comment]
@lunaryorn So the bug in web-mode run-mode-hooks is not coming from flycheck? We were just trying to understand what that message means. If we get web-mode to implement the run-mode-hooks, then maybe it would be valid.

As for eslint not being supported with web-mode, well then that raises the question as to **why using jsxhint works fine with web-mode and flycheck.**

Since eslint is supposed to be doing the same things jsxhint did, **why would jsxhint work fine, yet eslint is invalid?**

Here is my setup for using **jsxhint with web-mode and flycheck which works well**. It is limited to .jsx files, so it doesn't cause issues for other web-mode uses.

```lisp
(require 'flycheck)
;; flycheck jsxhint for jsx files
(flycheck-define-checker jsxhint-checker
  "A JSX syntax and style checker based on JSXHint."

  :command ("jsxhint" source)
  :error-patterns
  ((error line-start (1+ nonl) ": line " line ", col " column ", " (message) line-end))
  :modes (web-mode))
(add-hook 'web-mode-hook
          (lambda ()
            (when (equal web-mode-content-type "jsx")
              ;; enable flycheck
              (flycheck-select-checker 'jsxhint-checker)
              (flycheck-mode))))
```

**I changed the setup swapping out jsxhint for eslint and that's when I get the error**

```lisp
(require 'flycheck)
;; flycheck jsxhint for jsx files
(flycheck-define-checker jsxhint-checker
  "A JSX syntax and style checker based on JSXHint."

  :command ("jsxhint" source)
  :error-patterns
  ((error line-start (1+ nonl) ": line " line ", col " column ", " (message) line-end))
  :modes (web-mode))
(add-hook 'web-mode-hook
          (lambda ()
            (when (equal web-mode-content-type "jsx")
              ;; enable flycheck
              (flycheck-select-checker 'javascript-eslint)
              (flycheck-mode))))
```

**Comment by jeffbski** [comment]
web-mode + flycheck + jsxhint setup is discussed here:

http://truongtx.me/2014/03/10/emacs-setup-jsx-mode-and-jsx-syntax-checking/

**Comment by lunaryorn** [comment]
I said that I do not *know* where the message about run-mode-hooks comes
from, and I do not know what it means either.

Your jsxhint checker works with Web Mode because you *defined* it that way,
by adding Web Mode to the `:modes` of your checker.  The built-in
eslint checker of Flycheck however is not defined that way—it only supports
plain JavaScript modes. This is intentional—it's hard for Flycheck to
support Web Mode properly since it throws so many different languages into
one mode.

**Comment by jeffbski** [comment]
ok. Thanks for responding. I'll dig into the code and see if I can figure it out, comparing javascript-jsxhint and javascript-eslint.

**Comment by jeffbski** [comment]
Maybe I'll understand better once I go through the code for each.

**Comment by lunaryorn** [comment]
@jeffbski So no offense meant, but did you really just copy the code from the blog post without understanding what it actually does, and how a Flycheck syntax checker definition works?

Anyhow, as I said before, you can allow Flycheck to use eslint in Web Mode by adding the following code to your init file:

```cl
(flycheck-add-mode 'javascript-eslint 'web-mode)
```

**Comment by jeffbski** [comment]
@lunaryorn yes, more or less guilty. My emacs lisp understanding is minimal, so I sometimes copy and tweak. I just haven't spent the time to understand it all yet. 

Thanks for clarifying what you meant above.

Using that I was able to get everything working. My resulting setup is:

```lisp
;; use web-mode for .jsx files
(add-to-list 'auto-mode-alist '("\\.jsx$" . web-mode))
(defadvice web-mode-highlight-part (around tweak-jsx activate)
  (if (equal web-mode-content-type "jsx")
      (let ((web-mode-enable-part-face nil))
        ad-do-it)
    ad-do-it))

(require 'flycheck)
;; disable jshint since we prefer eslint checking
(setq-default flycheck-disabled-checkers (append flycheck-disabled-checkers '(javascript-jshint)))
;; enable flychecking for js-mode
(add-hook 'js-mode-hook (lambda () (flycheck-mode t)))
;; use eslint with web-mode for jsx files
(flycheck-add-mode 'javascript-eslint 'web-mode)
;; flycheck eslint for jsx files
(flycheck-define-checker eslint-jsx-checker
  "A JSX syntax and style checker based on ESLint."

  :command ("eslint" source)
  :error-patterns
  ((error line-start (1+ nonl) ": line " line ", col " column ", " (message) line-end))
  :modes (web-mode))
(add-hook 'web-mode-hook
          (lambda ()
            (when (equal web-mode-content-type "jsx")
              ;; enable flycheck
              (flycheck-select-checker 'javascript-eslint)
              (flycheck-mode))))
```

Thanks again for the help. Have a great day.

**Comment by lunaryorn** [comment]
@jeffbski So I presume this also fixed the message about `run-mode-hooks`?

With regards to your setup, please don't use `flycheck-mode` and `flycheck-select-checker` in a mode hook.  Instead enable Global Flycheck Mode and let Flycheck select the best checker for you.

Also, `(setq-default flycheck-disabled-checkers '(javascript-jshint))` is sufficient, since this variable is empty by default.

I should like to call your attention to the [comprehensive Flycheck manual](http://www.flycheck.org/manual/latest/index.html), which tries to explain all important concepts of Flycheck in depth.  Please do read it before trying to configure Flycheck.  Should you find anything that is missing from the manual, or unclear, please do not hesitate to open an issue and ask for further clarification or extension of the manual.

**Comment by jeffbski** [comment]
Yes, that fixed the run-mode-hooks. 

I'll read the flycheck manual and change my setup to using global flycheck mode and letting flycheck select best one for me. 

For the disabled checkers, I didn't want to assume that they hadn't customized flycheck-disabled-checkers elsewhere so I did an append.

Thanks for the help.

**Comment by lunaryorn** [comment]
@jeffbski Fancy.  I really wonder where that message came from.  Seems that Emacs doesn't deal well with errors from major mode hooks…

Anyhow, I'm happy that we could fix this issue, and get Flycheck working for you.  I really hope that you'll be able to enjoy Flycheck flawlessly from now on.  Should you have any other problems, please don't hesitate to open another issue!

**Comment by jeffbski** [comment]
Yes, thanks. I am looking forward to using flycheck for all my syntax checking and linting needs in emacs. I appreciate all your work to create this great project.

**Comment by jeffbski** [comment]
FYI. Using your advice to use global flycheck mode, my setup simplifies to:

```
;; use web-mode for .jsx files
(add-to-list 'auto-mode-alist '("\\.jsx$" . web-mode))

;; http://www.flycheck.org/manual/latest/index.html
(require 'flycheck)
;; turn on flychecking globally
(add-hook 'after-init-hook #'global-flycheck-mode)
;; disable jshint since we prefer eslint checking
(setq-default flycheck-disabled-checkers (append flycheck-disabled-checkers '(javascript-jshint)))
;; use eslint with web-mode for jsx files
(flycheck-add-mode 'javascript-eslint 'web-mode)
```
