### ISSUE TITLE
flycheck will make Emacs (even my computer) stuck.

### ISSUE THREAD

**Issue by c02y** [flycheck/flycheck#614]
Flycheck will make Emacs and my computer stuck, I cannot do anything but switch Ctrl-Alt-F2 to kill the Xorg then re-login or restart my computer.

When I just open my init.el in Emacs, move with C-v or M-v, seconds later, the whole buffer and Emacs and computer will stuck, the only thing I can see in the screen is the very slowly red wave character by character under the warning or error sentence in my init.el file.

All configuration about flycheck:

    (add-hook 'prog-mode-hook 'flycheck-mode)

The same result if I add 

    (setq flycheck-highlighting-mode 'lines)

or 

    (setq flycheck-highlighting-mode 'columns)

Default value is `symbols`

Of course, If I disable flycheck, the stuck will not happen.

FYI:
CentOS 6.5 32-bit
Emacs 24.4.1 (compiled from the source code at the official gnu website)
Flycheck-20150307.728

The same configuration will not happen in my home computer.
FYI:
Fedora 21 32-bit
Emacs 24.4.1 (from yum repo)
Flycheck (every single version, keep up to the latest version)

**Comment by lunaryorn** [comment]
@c02y Now, if even you can't reproduce this issue consistently on different systems, how am I supposed to reproduce, let alone debug it, with so little information?   Can you give me *any* other clue or information about this issue?  Can you reproduce the issue with other packages?  Flymake probably, because it uses a similar display code?  Do you have other display issues with Emacs on this system?

At a (very) wild guess, you could try to change the Flycheck faces to not use wave underlines (probably no underlines at all to be sure), and hope that this fixes the issue.

Ultimately I tend to blame your specific system for this issue, though.  Flycheck does not use Emacs' display system in any unusual way, so there's no immanent reason why it should break in your specific case, and I have little hope that we can find anything related to Flycheck in this case.

**Comment by lunaryorn** [comment]
@c02y Can you provide any new debugging information for this issue?

**Comment by lunaryorn** [comment]
Closing due to the lack of activity.
