### ISSUE TITLE
Clang checker discards extra lines in errors

### ISSUE THREAD

**Issue by Ralith** [flycheck/flycheck#615]
This makes flycheck very unhelpful for errors in a header file that only manifest when used, as typically occurs e.g. with template expansions. It's not viable to display full C++ errors all the time, as they can be ridiculously verbose, but it would be extremely helpful to have a way to obtain a buffer containing the full text of any given error on demand, or something similar.

**Comment by lunaryorn** [comment]
@Ralith Would you mind to give me a specific example, please?

**Comment by Ralith** [comment]
```c++
// foo.h
template<typename T>
void foo(T t) { return t.bar(); }
```
```c++
// main.cpp
#include "foo.h"

int main(int, char**) {
  foo(42);
}
```

Here flycheck annotates foo(42); with info "in instantiation of function template specialization 'foo<int>' requested here" and #include "foo.h" with error "In include /home/ralith/tmp/foo.h". I haven't been able to find any way to get the actual text of the error in foo.h, since the buffer for foo.h itself, containing no actual errors when considered on its own, is clean.

**Comment by lunaryorn** [comment]
@Ralith Please give me a complete example.  Specifically, show me the actual output of Clang (e.g. `C-c ! C-c c/c++-clang`) in addition to what Flycheck shows you in the error display.

**Comment by Ralith** [comment]
```
-*- mode: compilation; default-directory: "~/tmp/" -*-
Compilation started at Thu Apr  2 11:30:16

clang -fsyntax-only -fno-color-diagnostics -fno-caret-diagnostics -fno-diagnostics-show-option -iquote /home/ralith/tmp/ -std\=c\+\+14 -Wall -Wextra -x c\+\+ /home/ralith/tmp/main.cpp
In file included from /home/ralith/tmp/main.cpp:1:
/home/ralith/tmp/foo.h:2:24: error: member reference base type 'int' is not a structure or union
/home/ralith/tmp/main.cpp:4:3: note: in instantiation of function template specialization 'foo<int>' requested here

Compilation exited abnormally with code 1 at Thu Apr  2 11:30:16
```
```
    1     error           In include /home/ralith/tmp/foo.h... (c/c++-clang)
    4   3 info            in instantiation of function template specialization 'foo<int>' requested here... (c/c++-clang)
```

**Comment by Ralith** [comment]
I guess the problem isn't additional lines being discarded so much as errors located in one file but only detectable while processing another being discarded.

**Comment by lunaryorn** [comment]
@Ralith I'm not sure whether we can really handle these errors reasonably in Flycheck.  If I understand the output correctly the error manifests in the header file.  We can't just show the messages from the header file, though, since it might have many unrelated warnings which you'd normally like to ignore.

I guess we could get away with including *errors* from header files, while still omitting warnings, etc., but it feels like a hack.  Do you have other ideas?

And ultimately, to me this appears to be a corner case, which I don't want to spend a lot of time fixing personally.  If you have a reasonable fix, please open a pull request.

**Comment by Ralith** [comment]
I don't find I ever want to ignore even warnings in headers in my editing/build process. If a header is from an external library and contains harmless warnings, I specify its include path with -isystem to suppress the messages at the compiler level. 

In light of that, I'd be happy to see all messages--not just the ones applying to the current file--show up in the error list buffer. That said, running `C-c ! C-c c/c++-clang` manually is an adequate workaround for me, as it resolves the problem of not being able to see the error without running a build.

**Comment by lunaryorn** [comment]
@Ralith `C-c ! C-c` is intended for debugging.  It shouldn't be part of your regular workflow.  You should rather use `compile` and run a complete build.

Flycheck won't show you all errors from includes.  That's not it's job.  It'll only show you those errors that directly relate to the current file.  Even if it could somehow highlight all those errors in the current file, that's not an option, because most users actually *want* this behaviour. 

The issue at hand is that some errors manifest themselves in include files, but actually directly relate to the current file.  And I'm not sure whether Flycheck has any chance to figure that out.

And generally, Flycheck is *not* a substitute for your build system.  The error list is designed to show you the errors from the current buffer, not from the project as a whole.

**Comment by Ralith** [comment]
I could imagine Flycheck to do some sort of backwards scan through the output beginning at messages that match 'note: in instantiation of' and gathering all messages that refer to different files. This would still catch some messages that genuinely have nothing to do with the source file--if nothing else, actual mistakes in template definitions would be impossible to distinguish. A similar approach could also improve error reporting for misused macros. Literally adding an option to not filter the error list would be much simpler, though.

**Comment by lunaryorn** [comment]
That would not help.

Flycheck discards all errors that don't refer to the current file, because
there's no reasonable way to show them in the current buffer.  We'd somehow
need to map errors from includes to the corresponding include line to be
able to highlight errors in includes in the including buffer.

In fact Flycheck used to do that a while back, but I changed that at a
users request.  And I'm wary of changing it again and pissing off those
users that requested the change back then.

And to be honest, I'm a little fed up with this C/C++ include mess.  I'm
sorry, but I won't fix this issue myself.  It's too small a corner case for
me to spend any time on it, and I don't even use C or C++.

Feel free to try it yourself, though, I'll happily merge a pull request
that gets this right once and for all.

Am Samstag, 4. April 2015 schrieb Benjamin Saunders :

**Comment by lunaryorn** [comment]
@Ralith Closing as `wontfix`.  I'll not work on this myself.  Pull requests or patches welcome.
