### ISSUE TITLE
Errors when creating a file in non-existing directory

### ISSUE THREAD

**Issue by chillum** [flycheck/flycheck#625]
I do:

`C-x C-f /non/existent/dir/a.yml [RET]`

I get:

`Error while checking syntax automatically: (file-error "Setting current directory" "no such file or directory" "/non/existent/dir/")`

I bet, FlyCheck should't try to set the directory, unless it already exists (this happens when I save this new file in new directory for the first time).

**Comment by lunaryorn** [comment]
@chillum Currently, Flycheck just uses the `default-directory` provided by Emacs.  Apparently this directory is not guaranteed to exist.  I guess Flycheck eventually has to support this case, but I think it's a rather unusual corner case: You're the very first person to report this issue, even though it existed in Flycheck since its very beginning over two years ago.

I'll fix it, but only after #312 is implemented, since I don't want to touch the same code twice.  #312 is planned for the next release, but doing it properly needs some internal refactoring, and probably some breaking changes.  In other words, please don't expect this issue being fixed any time soon.

**Comment by lunaryorn** [comment]
@chillum Flycheck does not check files anymore if the containing directory does not exist.  You'll get no syntax checking, but at least Flycheck doesn't signal errors.

**Comment by chillum** [comment]
@lunaryorn yay! just updated the flycheck and it works just as I expected it to. thanks!

**Comment by lunaryorn** [comment]
@chillum You're welcome.  I'm glad that it now works for you :)
