### ISSUE TITLE
Multiline error messages

### ISSUE THREAD

**Issue by duud** [flycheck/flycheck#637]
Please don't strip error messages in flycheck-list-errors.
Currently I'm seeing a stripped error message:

In file included from include/linux/slab.h....

instead of:

In file included from drivers/gpu/drm/i915/i915_irq.c:32:
In file included from include/linux/slab.h:14:
In file included from include/linux/gfp.h:5:
In file included from include/linux/mmzone.h:7:
In file included from include/linux/spinlock.h:50:
In file included from include/linux/preempt.h:10:
In file included from include/linux/list.h:8:
In file included from include/linux/kernel.h:10:
In file included from include/linux/bitops.h:36:
In file included from arch/ia64/include/asm/bitops.h:18:
In file included from arch/ia64/include/asm/intrinsics.h:11:
arch/ia64/include/uapi/asm/intrinsics.h:15:10: fatal error: 'asm/ia64regs.h' file not found

Such a deep nesting is pretty common in C. Now I have to open each include file to reach the actual error.
Each of this includes may contain also nested errors so I have to open 50 files to see the actual error messages.
This is a huge usability problem which is easily solvable. So please don't strip multiline messages in flycheck-list-errors.

**Comment by lunaryorn** [comment]
Flycheck does not “strip” multiline error messages.  It parses all of these as individual error messages, and discards them because they are not from the current file obviously.

It's not “easily solvable”, either.  I've have changed this part of the code three times now, in response to various complaints, and never managed to make everyone happy.  Search for "C++ include" in Flycheck's issues here on Github to find past discussions of this.

Now, I don't use C or C++, and I find my time too precious to constantly change the parsing of C/C++ include errors back and forth.  Feel free to implement a better handling of these error messages, but if you try, please consider all of the past discussions and address all issues therein.  I'm not going to merge a patch that's just shifting the problem around without solving it.

Closing as wontfix.

**Comment by duud** [comment]
There are no general problems with the way how Flycheck handles c/c++ includes on a file leve, it's fine. But as a general design rule for Flycheck: there must be allways a place where you can review the whole errormessage. This applies not only to C/C++ but to every language/checker. This makes flycheck more robust and saves work. If Flycheck interprets an errormessage wrong or the compiler modifies its error syntax you can just look up the message yourself. flycheck-list-errors seems to be a natural place for it. Maybe I'm missing something and there is a way to review the whole error message.
