### ISSUE TITLE
package-compute-transaction: Package `let-alist-1.0.1' is unavailable

### ISSUE THREAD

**Issue by bluekeys** [flycheck/flycheck#643]
When I try and install flycheck mode I receive this error.

package-compute-transaction: Package `let-alist-1.0.1' is unavailable

I believe the package has been removed from melpa / marmalade

**Comment by lunaryorn** [comment]
@bluekeys let-alist is part of [GNU ELPA](http://elpa.gnu.org/packages/let-alist.html), the default package archive.  Please ensure that GNU ELPA is enabled in your Emacs—check the `package-archives` option—and try `M-x package-refresh-contents` before installing Flycheck.

Closing, since this is definitely an issue with your configuration.   Feel free to add further comments and questions, though, if you need more help on this problem.
