### ISSUE TITLE
New checker for phplint

### ISSUE THREAD

**Issue by Fuco1** [flycheck/flycheck#652]
Hello.  I couldn't find an existing checker for the PHPLint tool (http://www.icosaedro.it/phplint/) so I created one at https://github.com/Fuco1/flycheck-phplint

Please check if I'm doing things right and if so we might transfer the repo under flycheck org (if you so desire).

Thanks :)

**Comment by lunaryorn** [comment]
@Fuco1 I'd rather prefer to add the syntax checker to Flycheck itself.  If you agree, please open a pull request.  Reviewing is easier for me then.

**Comment by lunaryorn** [comment]
And if you don't agree, keep the repo under your username and maintain it on your own.  I don't want separate repos for simple syntax checkers, that wouldn't scale.

**Comment by lunaryorn** [comment]
Closing.

**Comment by Fuco1** [comment]
Right, I wasn't sure what the policy is when there seems to be a bunch of extra packages.  I'll turn it into a PR and get rid of the repo.

**Comment by lunaryorn** [comment]
The default policy is to have all checkers in Flycheck.  

Extra packages are only for checkers with special non-standard dependencies and/or much very language specific code, or for checkers that I specifically don't want to maintain as part of Flycheck because there are issues with the underlying tool.
