### ISSUE TITLE
custom setting not work(error highlight can not only with underline, can not set check automatically)

### ISSUE THREAD

**Issue by xuxiangyang** [flycheck/flycheck#657]
Hi, flycheck was added to gnu eamcs-24.5. I upgraded 24.3 to 24.5, and changed flymake with flycheck.

But I was stuck with the error/warning highlight , I want to highlight with underline, I changed the flycheck-error face with emacs customize，but It not work.

And as soon as input a word, flycheck highlight some error, such as, I input left bracket, flycheck highlight    all the right words. I input more , it change the highlight area, flicker the highlight area. I changed the flycheck-check-syntax-automatically with emacs customize, but not work.

It looks like, I can not customize any features about flycheck, what can I do?

my config:

```lisp
(add-hook 'after-init-hook #'global-flycheck-mode)
(custom-set-variables
 '(flycheck-check-syntax-automatically (quote (save new-line)))
 '(flycheck-idle-change-delay 1.5)
 '(flycheck-navigation-minimum-level (quote warning))
 '(safe-local-variable-values (quote ((encoding . utf-8)))))
(custom-set-faces
 '(flycheck-error ((t (:underline t))))
 '(flycheck-warning ((t (:underline t)))))
```

but it not work.....

![image](https://cloud.githubusercontent.com/assets/4926529/8040571/21002404-0e44-11e5-90ac-bfc0e63495f5.png)

I need some help..
Thank you

**Comment by lunaryorn** [comment]
@xuxiangyang I'm sorry but I fail to understand what this issue is about.

Your face customizations *did* work apparently:  As you can see in your screenshot, the highlighting uses underlines now (whereas in the default style, it'd use wave underlines).  If you want to have only underlines and no color, you need to remove the background and foreground colors, too.

I don't understand why you changed `flycheck-check-syntax-automatically`.  This option is not related to highlighting at all.  And your customization of `flycheck-idle-change-delay` has no effect at all, because you removed `idle-change` from `flycheck-check-syntax-automatically`.  I mean no offense, but it looks a bit like you were just making wild guesses.  Please read the Flycheck manual and the docstrings of these options to understand what they are actually doing.

To illustrate your problem, please show me a *small* example code (in whatever language you want), and explain what you see, and what you'd like to see instead, ideally with screenshots.

**Comment by xuxiangyang** [comment]
sorry, I am a newer for emacs, I can not understand flycheck manual, because It does not look like emacs wiki. The manual only tell what the variable or face mean, but I can not change it with elisp，emacs wiki would tell me how to write elisp. 
I try very hard to custom flycheck, but I failed.

sorry, I will close the issue, read manual again

**Comment by lunaryorn** [comment]
@xuxiangyang I *do* expect that you are generally familiar with customizing and using Emacs.  I'm sorry, but I do not have the time to teach you Emacs.  Please walk through the Emacs tutorial and read the Emacs manual, specifically the section on [Customization](http://www.gnu.org/software/emacs/manual/html_node/emacs/Customization.html#Customization).

If you have *specific* questions about Flycheck options, please open a new issue, and I'll be happy to help you.
