### ISSUE TITLE
flycheck cannot step into directories

### ISSUE THREAD

**Issue by Nuk9** [flycheck/flycheck#658]
For the following emacs init.el:

    (add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
    (require 'init-benchmarking) ;; Flycheck gives error: Cannot open load file: init-benchmarking

The file tree looks like this:

    ~/.emacs.d/init.el
    ~/.emacs.d/lisp/init-benchmarking.el

Seems flycheck is not stepping into `lisp` directory and find `init-benchmarking.el` file. Is it a desired behavior?

**Comment by lunaryorn** [comment]
@Nuk9 Yes.  Flycheck does not automatically inherit `load-path`, because that is usually not desired while developing Emacs Lisp packages.   Instead it maintains its own load path setting for Emacs Lisp, in `flycheck-emacs-lisp-load-path`.  Please read the docstring of this variable for more details.

And please do read the Flycheck manual, for this case specifically the [Emacs Lisp](http://www.flycheck.org/manual/latest/Supported-languages.html#Emacs-Lisp) section, which lists all options.
