### ISSUE TITLE
Switch checker javascript-eslint back to reading from stdin

### ISSUE THREAD

**Issue by P-Seebauer** [flycheck/flycheck#670]
Eslint has a [`--stdin-filename`](
http://eslint.org/docs/user-guide/command-line-interface#stdin-filename) option since version [0.21.0](
https://github.com/eslint/eslint/releases/tag/v0.21.0) (released on May 9th, so quite new). 
Maybe it is possible to switch back to reading from stdin instead of creating a file and reading from there for the checking? With this option, the reasons for not reading from stdin aren't given anymore.

I have seen #447, but at that time, this command line option wasn't available. 
Is there a way to configure a checker based on its version?

*Edit*: I just realized that flycheck doesn't provide the source via stdin. Might that be possible?

**Comment by lunaryorn** [comment]
I'm not sure why you think that Flycheck used to feed eslint via standard input.  That was never the case.  Flycheck always passes files to syntax checkers, because Emacs 24.x does not support standard input for asynchronous process—I hope that this changes in Emacs 25 (see #622), but currently it's just not possible.

Hence I don't know how I'm supposed to add this option to Flycheck.

**Comment by lunaryorn** [comment]
Closing as `wontfix`.

**Comment by lunaryorn** [comment]
Flycheck can't use standard input.  Rest assured that if it could, I'd have done that, but Emacs does not easily support standard input for asynchronous processes.  It might be possible—probably via comint, I don't know—but it's convoluted and hacky and probably not worth the (serious) effort.

**Comment by P-Seebauer** [comment]
Okay, thanks for the request. I might look into it. I think with `process-send-string` it might be achievable.
