### ISSUE TITLE
Easier include directories for C++ code

### ISSUE THREAD

**Issue by mruegenberg** [flycheck/flycheck#689]
It would be great to have an easier way of adding C++ include directories, especially per-project. 

I'm currently working on an OpenFrameworks project and had to more or less manually find 20-30 include directories and add them to `flycheck-clang-include-path`. The required information should be mostly contained within my Makefile.

Alternatively, I'd appreciate pointers on how to just ignore some include files, since I only really care about a very few includes in a specific directory, but get an error if the others aren't found. (Not sure whether this is practical, since Clang presumably wants those files when running its syntax checker.)

**Comment by lunaryorn** [comment]
I'm not sure what you're after with this issue.  Do you have any concrete proposals for how this "easier way" would look like?

Besides you may want to take a look at MELPA and GitHub.  There are some extensions like Flycheck Irony that supposedly simplify and improve the user experience in C/C++ projects.

**Comment by mruegenberg** [comment]
Unfortunately, I don't have a concrete idea. It just seems like the process should be easier. (An example of how to do this correctly in .dir-locals.el with support for wildcards would certainly help.)
I'll take a look at Irony.

**Comment by lunaryorn** [comment]
@mruegenberg Ultimately, it's all just a matter of writing the appropriate Emacs Lisp… it shouldn't be too difficult to parse your specific Makefile and extract the include directories from it.

But it's very hard and very cumbersome to get that right in a generic way, because there are so many different build systems for C++, and so many different styles of Makefiles.
