### ISSUE TITLE
Questions regarding executables which use wrappers

### ISSUE THREAD

**Issue by purcell** [flycheck/flycheck#702]
Let's say that instead of `hlint`, I would like to run `stack exec hlint`. Currently I can set `flycheck-haskell-hlint-executable` to either `nil` or a string, but `(executable-find "stack exec hlint")` naturally fails. Would it make sense to allow executables to be set to lists?

The downside of this is that a wrapper script might be executable, while the command it wraps is not, so that the wrapper will fail every time it is run. But this is also a (semi-related) problem for us `rbenv` users: for example, `~/.rbenv/bin/rubocop` will always be on the path, but will fail noisily inside any ruby project directory which does not have that gem installed.

So a second thought/suggestion is that it would be nice to be able to specify a per-checker sanity check for executables which goes beyond just verifying that they are present on the `$PATH`. For example, "run with `--version` and expect a zero exit code", or even "check that the output of `checker --version` contains a version string greater than 0.2.2".

**Comment by lunaryorn** [comment]
@purcell I'm not sure how to deal with such wrappers.  You can use `:predicate` to add custom checks, and Flycheck does that already for some checkers (e.g. `go-vet`), but I'm not sure whether that's the best approach.

For `stack` specifically, though, you can run `stack install hlint`, which will install `hlint` globally in `~/.local/bin/`.

**Comment by purcell** [comment]
If I recall correctly from working on it recently, `syntastic` always does a version check by default. I guess it trades off that extra `exec` for some assurance that the checker will actually work when needed. I think this is the best trade-off in the end.

Re. `stack`, the example of `hlint` wasn't the best one for me to give. More specifically, `stack exec -- ghc -fno-code -Wall ...` conveniently makes ghc inherit the stack library environment, cutting `cabal` out of the picture. So as stack gains in popularity I'd quite like to figure out how to use flycheck seamlessly with it. I think that allowing the executable var to be set to `("stack" "exec" "--" "ghc")` might do the trick.

**Comment by lunaryorn** [comment]
@purcell I'll add a separate syntax checker for `stack ghc` (there's a branch for it already, see `feature/stack-ghc`), because that works better for the user in my opinion.  Flycheck could automatically use `stack ghc` for projects with `stack.yml` and standard `ghc`—if installed—for project without, without any manual configuration required.

As for the version check, we'd have to add an extra command line for that, i.e. `:version-command`, because there's no standard for `--version`, and a regexp matching the expected output, because we can't rely on exit codes either.  And that's a lot of work for all syntax checkers, for very little gain, at least from my point of view.

**Comment by purcell** [comment]
> @purcell I'll add a separate syntax checker for stack ghc (there's a branch for it already, see feature/stack-ghc), because that works better for the user in my opinion. Flycheck could automatically use stack ghc for projects with stack.yml and standard ghc—if installed—for project without, without any manual configuration required.

Great, agreed.

> As for the version check, we'd have to add an extra command line for that, i.e. :version-command, because there's no standard for --version, and a regexp matching the expected output, because we can't rely on exit codes either. And that's a lot of work for all syntax checkers, for very little gain, at least from my point of view.

I agree it's a bit of work, but all the ruby-based ones (sass, rubocop, ruby, haml, sqlint) currently crash out noisily with an exit code of `127` and no recognisable errors if they are not gem-installed in the current `rbenv` (and `rvm`?) project environment or globally, but are installed in some other `rbenv` project dir. This is because the shim wrapper will have been created on the $PATH, but will only work properly from that other project dir.

It's not a huge deal, but that's also a tangible failure case, at least for those of us stuck with ruby. ;-)

**Comment by lunaryorn** [comment]
@purcell I tend to conveniently blame `rbenv` and it's questionable concept of shims :)  Seriously, though, from my point of view, it's a lot of effort for just a single programming language whose toolchain is arguably flawed.

I've opened #711 for a stack-based syntax checker, and I'll add it asap, because it's something I really miss myself, but I don't think that I'll add a generic version-check feature myself.  For my point of why, it's just not worth the effort.

Closing as `wontfix`.
