### ISSUE TITLE
flycheck and javascript-eslint create temp files in source tree that cause build tools to choke

### ISSUE THREAD

**Issue by sunwukung** [flycheck/flycheck#717]
I have been having a [similar issue as this user on stack](http://emacs.stackexchange.com/questions/13911/how-to-set-temporary-file-directory-for-flycheck-eslint-outside-of-current-dire) (which I saw you respond to)

When testing JS with mocha (often via gulp/grunt) you specify a glob to identify all the test files - mocha then watches those files, and barfs when flycheck writes (and removes) that file from the watched directory. Mocha doesn't supply any easy means of excluding files - and has rejected calls to do so (see [mocha issue 1577](https://github.com/mochajs/mocha/issues/1577)).

One workaround is to run mocha from the cli and manually identify all the files then pipe/xarg them to mocha after the fact, so that it would ignore any subsequent generated files. This doesn't lend itself well to contemporary tooling solutions (i.e. gulp/grunt/webpack) - or in projects with multiple members using different editors.

I see in your response that flycheck needs those files to be written in the same directory to work properly - do they have to share the same extension as the files under lint? I'm an elisp noob so I doubt I would be able to contribute anything meaningful - but perhaps you could help me understand why this needs to be the case?

**Comment by lunaryorn** [comment]
@sunwukung I don't know whether they need to have the same extension.  I never tried.  I never even thought of this, since hitherto I was under the impression that repeatable builds were an absolute requirement for decent software engineering, which of course includes knowing which files your build system touches and which not.  Apparently I'm wrong, the Javascript community seems to have vastly different standards here :unamused: 

Note, though, that you can already change the prefix of these temporary files via `flycheck-temp-prefix`.  I don't know how Mocha works, but if you're lucky then it ignores hidden files, and you can change `flycheck-temp-prefix` to `".flycheck"`, i.e. mark the temporary files as hidden, and thus have Mocha ignore them.

The default value of this variable won't change, though, because there are some syntax checker (e.g. Rust, iirc) that don't handle hidden files well.

Beyond that, it's not a problem that I want to invest a lot of hours in fixing.  See #673 for an alternative, that I aim to add to Flycheck as soon as possible, in order to entirely do away the need for temporary files.

**Comment by lunaryorn** [comment]
@sunwukung Does that answer your question?

**Comment by sunwukung** [comment]
> I was under the impression that repeatable builds were an absolute requirement for decent software engineering, which of course includes knowing which files your build system touches and which not. Apparently I'm wrong, the Javascript community seems to have vastly different standards here

You could list all the files in your source tree explicitly to make sure, but that's a lot of hard work - especially in a large project. Globbing exists to avoid that problem - and thus here we are. I guess there's a (misplaced?) assumption is that the files in the source directory are ones you own, rather than ones that your editor has deposited there.

I'll take a stab at the prefix approach, see if that fixes it. Thanks for your time (and flycheck!)

**Comment by lunaryorn** [comment]
@sunwukung 

> I guess there's a (misplaced?) assumption is that the files in the source directory are ones you own, rather than ones that your editor has deposited there.

I don't know.  My assumption would be that there's an exact definition of what files should be build and how, so that my system doesn't build any random file that happens to appear in my source tree, for whatever reason, with arbitrary settings.  Isn't that the basic idea of repeatable builds?

But we digress, sorry for that.

Please do try to change the prefix, and if that doesn't work, please open a new issue.  In this case Flycheck should give you even more control about the temporary file name, and probably allow you to make arbitrary substitutions/transformations such as using a different extension, that go beyond just changing the prefix.   Alternatively, I'll then probably put standard input support as in #673 on top of my backlog and try to add it asap, to entirely remove the root cause of this issue, which has caused major nuisances in the past, too.

Thanks for you feedback, and I hope that Flycheck works well for you nonetheless.
