### ISSUE TITLE
Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 1, but no errors from output

### ISSUE THREAD

**Issue by vigneshsarma** [flycheck/flycheck#720]
Stacktrace:
```python
Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 1, but no errors from output: Traceback (most recent call last):
  File "/Users/vignesh/.venvs/imojo-d7/bin/flake8", line 7, in <module>
    from flake8.main import main
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/flake8/main.py", line 6, in <module>
    import setuptools
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/setuptools/__init__.py", line 4, in <module>
    import distutils.core
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 10, in <module>
    from email import message_from_file
  File "/Users/vignesh/code/imojo/utils/email.py", line 12, in <module>
    from mail_templated import EmailMessage
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/mail_templated/__init__.py", line 1, in <module>
    from django.core import mail
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/django/core/mail/__init__.py", line 14, in <module>
    from django.core.mail.message import (
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/django/core/mail/message.py", line 8, in <module>
    from email import (charset as Charset, encoders as Encoders,
ImportError: cannot import name charset

Checker definition probably flawed.
```

Versions
```
Flycheck version: 0.24snapshot (package: 20150809.819)
GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.1, NS apple-appkit-1345.38) of 2015-06-02
-------------
flake8 --version
2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 2.7.10 on Darwin
```

Running flake8 outside flycheck, in the same virtualenv causes no issue. I am also able to import `charset` in the same env without issues.

**Comment by lunaryorn** [comment]
@vigneshsarma I'm sorry, but that's not a Flycheck problem.  Flycheck doesn't change the environment for syntax checker tools, and I'm using virtualenv executables in Flycheck just fine.  Whatever is causing `flake8` to fail in Emacs comes from somewhere else.a

Try to run `flake8` from `M-x shell`, and via `M-: (process-lines "flake8" "--version")`.  Check the environment variables of your Emacs session, and make sure that you enabled the right virtualenv in your session.

Closing as `invalid`.  Please feel free to add further details, and I'll re-open the issue if it turns out to be a Flycheck issue.

**Comment by vigneshsarma** [comment]
Is there any way to see the exact command that is being executed?(A good place to put debugger or log?)

Everything else seems to be working fine.

```elisp
ELISP> (process-lines "flake8" "--version")
("2.4.1 (pep8: 1.5.7, pyflakes: 0.8.1, mccabe: 0.3.1) CPython 2.7.10 on Darwin")
ELISP> (call-process "flake8" nil t nil "utils/email.py")
1 (#o1, #x1, ?\C-a)
utils/email.py:72:80: E501 line too long (80 > 79 characters)
```

**Comment by lunaryorn** [comment]
@vigneshsarma `C-c ! C-c python-flake8`.

**Comment by vigneshsarma** [comment]
The issue seems to be that since we have a local module `email`, while the import should be from std lib its throwing up. Check the `eshell` session at the bottom.

A reasonable solution would be for me to always run the `flake8` from the project root. Since the command is giving the full path of the file, is there a way to set the current path(`pwd`) to project root before running the command?

In my case I will be able to get project root from projectile.

```
(imojo-d7) imojo $ flake8 --format=default /Users/vignesh/code/imojo/utils/email.py
/Users/vignesh/code/imojo/utils/email.py:5:1: F401 'os' imported but unused
/Users/vignesh/code/imojo/utils/email.py:14:1: E302 expected 2 blank lines, found 1
(imojo-d7) imojo $ cd utils/
(imojo-d7) utils $ flake8 --format=default /Users/vignesh/code/imojo/utils/email.py
Traceback (most recent call last):
  File "/Users/vignesh/.venvs/imojo-d7/bin/flake8", line 7, in <module>
    from flake8.main import main
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/flake8/main.py", line 6, in <module>
    import setuptools
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/setuptools/__init__.py", line 4, in <module>
    import distutils.core
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/distutils/__init__.py", line 25, in <module>
    from distutils import dist, sysconfig
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 10, in <module>
    from email import message_from_file
  File "/Users/vignesh/code/imojo/utils/email.py", line 12, in <module>
    from mail_templated import EmailMessage
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/mail_templated/__init__.py", line 1, in <module>
    from django.core import mail
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/django/core/mail/__init__.py", line 14, in <module>
    from django.core.mail.message import (
  File "/Users/vignesh/.venvs/imojo-d7/lib/python2.7/site-packages/django/core/mail/message.py", line 8, in <module>
    from email import (charset as Charset, encoders as Encoders,
ImportError: cannot import name charset
```

**Comment by fbergroth** [comment]
@vigneshsarma don't make implicit relative imports. If you want to do relative imports, use `from .email import message_from_file`. You can turn off implicit relative imports with `from __future__ import absolute_import`, which is the default in python3.

**Comment by vigneshsarma** [comment]
@fbergroth I know!!! This is not a relative import at all. Let me try to explain.

* Imagine there is a module `foo` in python standard lib. Which you use as `from foo import x`.
* Now in your project you create a new module `abcd.foo`.
* In the module `abcd.foo` you use a library `baz` which imports from `foo` in std lib.
* If you execute python at project root, everything will work correctly.
* If you execute python from `project_root/abcd` the lib `baz` will load `abcd.foo` as `foo`. As current dir is added at the top of `PYTHONPATH`.

This is my understanding of the situation. If I am missing something please tell me.

**Comment by fbergroth** [comment]
I see, my mistake.

**Comment by lunaryorn** [comment]
@vigneshsarma That _is_ a relative import, albeit an accidental one. 

You can't specify the working directory currently ( see #312), but you shouldn't allow relative imports anyway.  Use `from __future__ import absolute_imports`.  It fixes this issue and is good practice anyway, precisely because implicit relative imports, whether intentional or accidental, cause all sorts of troubles.

Marking as `wontfix`.

**Comment by fspegni** [comment]
Hi, I understand this bug is kind of closed but I found it through google for a very similar problem. My scenario was exactly as @vigneshsarma said: I was executing python not in `project_root` but in `project_root/abcd`, and I had to do that way.

My problem was that I set `PYTHONPATH=<somedirectory>:`; the final colon somehow tell python to look for modules in the current directory; just changing it to `PYTHONPATH=<somedirectory>` solved my problem. Perhaps it is the same on your case.

**Comment by giupo** [comment]
Thank you @fspegni : I had a `PYTHONPATH=""` in my `$HOME/.bash_profile` (probably junk left rushing doing something else). Removing it from my environment solved this issue with flycheck for me.

**Comment by Grimscythe1983** [comment]
What worked for me was uninstalling flake8 with (don't use sudo under windows) :
`sudo pip uninstall flake8'
`sudo pip2 uninstall flake8'
The second command was necessary as I run Python 2 and 3 (3 is my default).
And reinstall with:
`sudo pip install flake8'
`sudo pip2 install flake8'

And it just works again :/

**Comment by kislyuk** [comment]
@lunaryorn, the issue here is that you're running the linter (flake8) in the same directory as the file being checked, which has package namespace implications for Python. A nice way to work around this would be to run the linter in a temporary working directory, and refer to the linted file by its absolute path.
