### ISSUE TITLE
Flycheck for eclim

### ISSUE THREAD

**Issue by kleewho** [flycheck/flycheck#736]
I'd like to get your opinion about use of flycheck for eclim. I found this issue on ensime project https://github.com/ensime/ensime-emacs/issues/160 and basing on the file I found there created similar thing for eclim https://github.com/kleewho/emacs-eclim/tree/flycheck. I wonder what disadvantages it might have or what are things that I should know. I'm thinking about enabling it for users as an experimental feature. 

This feature is tracked as https://github.com/senny/emacs-eclim/issues/196 in eclim project

**Comment by lunaryorn** [comment]
@kleewho I'll be happy to review your code.  Please give me a direct link to the specific file where you use Flycheck in Eclim, for I don't want to browse the entire, rather large code base of Eclim.  No offense meant, but I simply don't have the time.

I'm not sure what you understand by “disadvantages”, and I wonder how I should be able to assess that, given that I do not know what your current solution is capable of and what problems it has.

Generally, Flycheck does support this kind of thing, more or less.  Specifically, Flycheck currently pretty much insists on triggering syntax checks by itself, and provides no proper API to have checks triggered from the outside, i.e. after Eclim has processed a buffer.  That makes its use a little awkward, but it shouldn't get in your way too much.

Another thing to be aware of is that asynchronous processing in Emacs is notoriously brittle and fragile, because of the lack of any proper concurrency primitives in the Emacs API.  You _may probably_ suffer from random freezes, dead locks or race conditions which will be hard to debug and hard to solve.  But that holds for Eclim, Ensime and similar tools generally, and if you haven't had this issues hitherto, chances are low that you'll get them with Flycheck.

Note that I'm currently away, and only occasionally connected to the net, so I might not get to review your code before the weekend after the next.  I'm sorry for that, and I'd like to ask for your patience on this issue :)

**Comment by lunaryorn** [comment]
@kleewho Any news on this?  Do you need further help?

**Comment by lunaryorn** [comment]
Closing due to the lack of activity
