### ISSUE TITLE
No obvious way to re-enable a checker after the error count transiently exceeds error limit

### ISSUE THREAD

**Issue by ngoldbaum** [flycheck/flycheck#748]
Often when editing a python file, a buffer will transiently exceed `flycheck-checker-error-threshold`. According to the resolution of #476, `flycheck-checker-error-threshold` was added to prevent syntax checking on buffers that produce thousands of errors.

Fair enough, but sometimes I will *transiently* introduce thousands of errors by e.g. typing a function definiton. Before I've finished typing, I trigger hundreds of syntax errors in the file, and flycheck disables the checker I'm using using until I restart emacs.  I see that I could remove the checker from `flycheck-disabled-checkers` as well, but that isn't clear from the error message, which looks like:

```
Syntax checker in buffer plot_window.py in python-mode:

  python-flake8
    - major mode: `python-mode' supported
    - predicate:  t
    - executable: Found at /usr/local/bin/flake8

Flycheck cannot use this syntax checker for this buffer.
```

Maybe this could be resolved by changing the message to explain that the reason why flycheck can't use the checker I'm looking for is that the checker is in `flycheck-disabled-checkers`. Maybe if I explicitly try switching the checker back to the one I want by using `M-x flycheck-select-checker`, flycheck could try running the checker to see if the number of errors still exceeds `flycheck-checker-error-threshold`.

**Comment by cpitclaudel** [comment]
Indeed, we can make it easier to re-enable flycheck in these cases. Re-enabling flycheck automatically is a lot harder, as simply parsing the list of errors is a costly process if it is long. Thus we can't just keep running the checker until we get a smaller list.

@lunaryorn: maybe one thing that we could do would be to stop processing the process output if it gets too big? In effect this would put a threshold not only on the number of errors, but also on the size of the error output; since the output is generated and received asynchronously, that threshold would not be very costly to enforce, and we could cancel the check without disabling the checker if the output size went over the size threshold.

**Comment by lunaryorn** [comment]
I tend to blame `flake8`.  As far as I know it's the only syntax checker that regularly hits this limit _transiently_, and I would not like to add workarounds for the issues of just one single syntax checker.

At most, I'd try to disable syntax checkers less aggressively, i.e. by averaging the number of errors over the last three or so checks, and only disable a checker if this average is higher than the limit.  That'd prevent this specific problem.

But before I implement this, I'd rather like to ask @ngoldbaum to try and increase `flycheck-checker-error-threshold` and `flycheck-idle-change-delay`, to make Flycheck check less aggressively and more tolerant to many errors.

**Comment by ngoldbaum** [comment]
I've in fact already increased `flycheck-checker-error-threshold` which had resolved the issue for the file I'm working on.

**Comment by lunaryorn** [comment]
@ngoldbaum What's your current threshold now?  Do you notice any lags, assuming that you have an average machine?  We might just be able to increase the default threshold, there's no particular reason behind the current value, it's just a wild guess of mine.

**Comment by ngoldbaum** [comment]
I have it set to 2000 now. I don't notice any perceptible lag but am using a pretty fast new laptop.

**Comment by lunaryorn** [comment]
@ngoldbaum Does `flake8` really emit 2000 errors following a _single_ syntax error in a function definition?

**Comment by lunaryorn** [comment]
@cpitclaudel I seem to have missed a part of [your comment](https://github.com/flycheck/flycheck/issues/748#issuecomment-141270734):

> Indeed, we can make it easier to re-enable flycheck in these cases. Re-enabling flycheck automatically is a lot harder, as simply parsing the list of errors is a costly process if it is long. Thus we can't just keep running the checker until we get a smaller list. 

I'm not sure, iirc the cost of parsing where entirely dwarfed by the cost of adding overlays.  I think we could easily implement a more sophisticated behaviour to temporarily disable syntax checkers, or even just suppress excessive overlays. 

The sole reason that Flycheck doesn't do that is my being lazy:  The current approach was only a quick hack build upon existing infrastructure in Flycheck to fix an apparent problem.  It was a cheap shot more than anything else :blush: 

We can definitely improve the current behaviour, but I see no urgent need: The issue only appears infrequently and does apparently not affect many users.  And it's easily fixed by either increasing the threshold, or by customizing Flycheck to check less aggressively.

**Comment by cpitclaudel** [comment]
@lunaryorn Indeed, it doesn't seem like a very pressing issue. I like your idea of putting an upper bound on the number of displayed errors. If the problem pops up again, we could just make the default error filter trim the list down to a fixed number :)

**Comment by lunaryorn** [comment]
@cpitclaudel Yes.  Meanwhile I'm closing this issue, since it's solved for @ngoldbaum

**Comment by felker** [comment]
Apologies for commenting on an old/closed Issue.

When I am editing a long C++ file, sometimes I will accidentally mistype on the first line, which causes `c/c++-gcc` to emit >900 syntax errors and be disabled. I have increased my error threshold as a workaround for these transient errors, but is there still no better way to re-enable a syntax checker other than restarting Emacs, @lunaryorn?

**Comment by lunaryorn** [comment]
I’m sorry but I can’t help you: I’m not involved in this project anymore.

Pease leave me out of this.

**Comment by fmdkdd** [comment]
> but is there still no better way to re-enable a syntax checker other than restarting Emacs

You can use `C-u C-c ! x` to enable a disabled checker (as hinted to by the verify-setup buffer).  No need to restart Emacs!

Though we may add a button to the verify-setup buffer to do that as well.

**Comment by cpitclaudel** [comment]
I think we could add details to the error message; WDYT, @fmdkdd?

**Comment by fmdkdd** [comment]
> I think we could add details to the error message; WDYT, @fmdkdd?

Agreed.  See the patch in #1562.

**Comment by fmdkdd** [comment]
Oops, didn't see #1580.  Nevermind!
