### ISSUE TITLE
Getting flycheck into ELPA

### ISSUE THREAD

**Issue by jwiegley** [flycheck/flycheck#801]
Hi @lunaryorn, I realize it will be a drag to track down assignment papers for everyone, but would you be willing to consider getting flycheck into ELPA, so that it can become a part of Emacs?

**Comment by lunaryorn** [comment]
I was afraid that you'd ask.  Unfortunately I'm not willing to move Flycheck into ELPA, let alone Emacs itself.  I see no practical advantage in such a move that'd be worth the considerable effort and outweigh the additional maintenance burden and the potential risks, and personally I'm not willing to contribute to Emacs as a project in its current form.  

Please don't take this personally; I think you're moving a lot of things into the right direction, and if it was just for you I'd instantly move Flycheck to Emacs.  But there's so large a gap between Emacs and what I consider a welcoming and comfortable project that being part of Emacs is absolutely not an option for me currently.

I'm sorry.

**Comment by jwiegley** [comment]
@lunaryorn I think it's always OK to be honest, especially between us. Maybe in a few years things will have improved enough to welcome you back; this is my goal.

**Comment by lunaryorn** [comment]
@jwiegley Thank you for understanding my concerns, and for not pressuring me :blush:  I really hope that you succeed in turning Emacs into a great open source project, and I wish you all the best :relaxed:

**Comment by lunaryorn** [comment]
@jwiegley I'm coming back to this issue because these days emacs-devel in all its glory has again reminded me why I refrain from contributing to Emacs:  I'd have to bear with ridiculous criticism and even what you might call aggressive action against my code.  

I think you're making a positive difference to Emacs, but its culture of communication and respect (or the lack thereof currently) has still a loooooooong way to go ere it becomes acceptable to me.

**Comment by jwiegley** [comment]
OK, cultural change is the slowest kind.  Maybe in another few years. :)

**Comment by rileyrg** [comment]
Interesting thread. Whole heartedly agree.
