### ISSUE TITLE
flake8 configuration files do not match tool defaults

### ISSUE THREAD

**Issue by sambrightman** [flycheck/flycheck#805]
As per http://flake8.readthedocs.org/en/latest/config.html, flake8 defaults to ~/.config/flake8 on Unix and ~/.flake8 on Windows. It also falls back to looking for tox.ini or setup.cfg. The default in Flycheck is to look for a file called '.flake8rc' which does not match either. This means that I cannot just setup flake8 using it's own configuration and expect Flycheck to work with it.

I would want the default to be nil and use the tool default but I'm guessing that this prevents scanning the project tree. Perhaps allowing multiple values would fix this?

**Comment by lunaryorn** [comment]
I'm not sure what the issue is.  Flycheck doesn't actually give a configuration file to `flake8` if it finds no file by that name.  If you don't have any `.flake8rc` files anywhere Flycheck invokes `flake8` _without_ `--config` and `flake8` should use its own configuration files.

Can you please describe the observed misbehaviour and provide a recipe to reproduce it?

**Comment by sambrightman** [comment]
Correct, I misunderstood the code at the same time as having incorrect configuration in the default location. It looked like it was always passing a parameter.

**Comment by lunaryorn** [comment]
Ah, ok, I'm happy that the problem is gone ☺️
