### ISSUE TITLE
pkg-info-version-info not defined

### ISSUE THREAD

**Issue by davidswelt** [flycheck/flycheck#814]
I have installed flycheck 0.25.1 on my Emacs 25.1 (built from Emacs-25 branch).  It's in the load path, and I've done (require 'flycheck), but nothing else.

The Tools menu now has a menu for syntax checking.  When I select "Show Flycheck Version", I get this error (see below).

I tried (require 'package) to debug this, but no luck.  This function isn't defined.

Debugger entered--Lisp error: (void-function pkg-info-version-info)
  (pkg-info-version-info (quote flycheck))
  (let ((version (pkg-info-version-info (quote flycheck)))) (if show-version (progn (message "Flycheck version: %s" version))) version)
  flycheck-version(t)
  funcall-interactively(flycheck-version t)
  call-interactively(flycheck-version nil nil)
  command-execute(flycheck-version)

**Comment by lunaryorn** [comment]
You need to install pkg-info for this command.  Emacs' package manager should have done that automatically.  How did you install Flycheck?

**Comment by davidswelt** [comment]
Manually.

Prerequisites in your info file does not list pkg-info as a prerequisite.  It seems you also rely on it being autoloaded (perhaps a “require” would be useful).
Is the dependency necessary only for this command?  Is it worth creating a dependency?

I’m preparing to provide flycheck with Aquamacs.  I’m happy to include pkg-info if need be.

**Comment by lunaryorn** [comment]
@davidswelt I'm not sure what you're talking about.  There must be a misunderstanding, because as far as I can see `pkg-info` is listed in the `Package-Requires` header.  It's only used for version information though which is why Flycheck does not load it up front but only in demand via autoloads.

Please note that we do neither support manual installation nor Aquamacs.  Emacs' package manager is the only official installation channel and GNU Emacs proper the only officially supported Emacs variant.
