### ISSUE TITLE
echo error at point (in minibuffer)

### ISSUE THREAD

**Issue by fommil** [flycheck/flycheck#834]
ENSIME has this (with `C-c C-v e`) and it is incredibly useful. Sometimes one sees red squigglies and it's nice just to be able to get a hint about what is going wrong.

**Comment by lunaryorn** [comment]
Thank you for this feedback!  I'm not sure, though, whether I understand you.  

Are you aware that Flycheck shows the error at point when you move the point to an error location?  Or would rather like to have an explicit key binding to show the error at point?  Do you know about the error list which automatically scrolls to and highlights the error at point?

**Comment by fommil** [comment]
I think I only get that error when I use the mouse (uugh). I have `eldoc` installed too and I think it tends to win the race to the minibuffer.

**Comment by cpitclaudel** [comment]
@fommil Could you try `C-h .` on an error?

**Comment by fommil** [comment]
@cpitclaudel oh, that does give me something in the minibuffer. Is that coming from flycheck? It seems built-in.

**Comment by cpitclaudel** [comment]
Flycheck sets the `help-echo` property on errors, so pressing `C-h .` (which is by default bound to `display-local-help`) does show the Flycheck error which the point is on.

That being said, flycheck also has its own mechanism for displaying errors, so placing the point on an error and waiting for a bit should show that error as well (in the minibuffer, on in a pop up if the message is long). But for the specific feature that you were asking about (a keybinding to show the current error) `C-h .` should do :)

**Comment by fommil** [comment]
That's great! More reason for us to use flycheck when it's ready.

**Comment by cpitclaudel** [comment]
Glad your problem is resolved :) But what do you mean by "when it's ready?"

**Comment by fommil** [comment]
@cpitclaudel #774

**Comment by cpitclaudel** [comment]
Got it, thanks!

**Comment by lunaryorn** [comment]
@cpitclaudel Nice, I didn't even know about `C-h .` :relaxed:

@fommil I've also added `C-c ! h` as a new binding which explicitly invokes Flycheck's error display for the error at point.  Unlike `C-h .` it uses whatever is configured for Flycheck's error display, so if you're using [flycheck-pos-tip](https://github.com/flycheck/flycheck-pos-tip) you'll get a GUI popup instead of an echo area message.  `C-h .` will always use the minibuffer.

I also took the opportunity to improve the corresponding section in our manual.   Please [take a look](http://www.flycheck.org/manual/latest/Displaying-errors.html#Displaying-errors) and tell me if you're missing anything.

Thank you very much for reporting this issue.

**Comment by fommil** [comment]
cool
