### ISSUE TITLE
Tests for haskell-ghc and haskell-stack-ghc broken in 0.25.1

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#888]
Hello,

The tests for the haskell-ghc and haskell-stack-ghc checkers are skipped in a clean Debian Sid chroot that has both ghc and stack installed and in $PATH (Emacs 24.5.1; flycheck 0.25.1).  Why might this be?

    SKIPPED  flycheck-define-checker/haskell-ghc/complete-chain
    SKIPPED  flycheck-define-checker/haskell-ghc/literate
    SKIPPED  flycheck-define-checker/haskell-ghc/syntax-error
    SKIPPED  flycheck-define-checker/haskell-ghc/type-error
    SKIPPED  flycheck-define-checker/haskell-stack-ghc/complete-chain
    SKIPPED  flycheck-define-checker/haskell-stack-ghc/literate
    SKIPPED  flycheck-define-checker/haskell-stack-ghc/syntax-error
    SKIPPED  flycheck-define-checker/haskell-stack-ghc/type-error

Thanks!

Sean

**Comment by lunaryorn** [comment]
@spwhitton Did you run `cask install` before?

**Comment by spwhitton** [comment]
Thanks for your reply.  I'm preparing a Debian package of flycheck (so users can just `apt-get install elpa-flycheck`) which means that I cannot use Cask.  I do, however, have haskell-mode, shut-up, let-alist, seq and dash all installed and available to Emacs.

**Comment by lunaryorn** [comment]
@spwhitton Well, the test cases need Haskell Mode; you must have Haskell Mode's autoloads loaded, otherwise the test will be skipped because the mode is missing.

----

Our whole tooling on the Emacs Lisp side, including our test suite, builds upon Cask.  Specifically we rely upon Cask to install all Emacs Lisp dependencies of the test suite.  If you look at `test/run.el` you'll see that we explicitly load packages from Cask's local package directory.

I do not know how you could run our test suite outside of Cask, and to be honest, I don't bother to find out.  I appreciate your efforts, but as far as we are concerned, Emacs' own package manager is the only supported way of installing Flycheck, and always will be.  I hope you'll understand that we can only provide very limited support for alternative packaging methods.

I am closing this issue as `invalid` as it concerns a package manager which we do not support.

**Comment by spwhitton** [comment]
I completely understand that you don't want to support Debian's package manager.  I'll see if perhaps the autoloads aren't loaded -- thanks for pointing me in that direction.

**Comment by lunaryorn** [comment]
In other words, as far as we are concerned you must have Cask to run the tests.  If you can't use Cask you are on your own, and have to take a look at the source code to find out whether it's even possible to run our tests without Cask.

Should you require changes to our tooling in our to build your Debian package, we'll gladly review corresponding pull requests.  Thank you very much.

**Comment by cpitclaudel** [comment]
@spwhitton Is there a reason to distribute Flycheck through Debian's package manager rather than MELPA? I'm happy to help too, of course, but I'm not sure whether `apt-get install elpa-flycheck` is simpler than `M-x package-install RET flycheck RET`, and I'm a bit afraid of the fragmentation.

**Comment by spwhitton** [comment]
@cpitclaudel Here's a few reasons:

- easier to automate the installation of flycheck when setting up a new OS installation
- the Debian archive is more trustworthy than MELPA at present:
  - MELPA still contains packages pulled from the publicly editable Emacs Wiki
  - MELPA does not yet verify signatures on downloaded packages
  - Emacs does not verify https server certificates by default

**Comment by cpitclaudel** [comment]
@spwhitton Thanks!
