### ISSUE TITLE
please add a flycheck-last-error function

### ISSUE THREAD

**Issue by wbolster** [flycheck/flycheck#896]
right now flycheck provides `flycheck-next-error`, `flycheck-previous-error`, `flycheck-first-error`, but no `flycheck-last-error`. i have a bunch of next/prev/first/last mappings (buffers, compilation errors, and so on), but currently there is a gap where `flycheck-last-error` fits in...

**Comment by lunaryorn** [comment]
I'm sorry but we will not provide `flycheck-last-error`.   `flycheck-first-error` exists for no other reason than consistency with the built-in `first-error` but since there's no `last-error` we don't need to define a `flycheck-last-error` either.

Both are entirely redundant as you can easily use `M-< C-c ! n` or `M-> C-c ! p` respectively.  If you really need this feature as a command you can easily define it yourself:

```cl
(defun flycheck-last-error()
  (goto-char (point-max))
  (flycheck-previous-error))
```

However that's far too trivial for us to provide ourselves, and I don't think anyone would use it.  I've not seen anyone using `flycheck-first-error`/`first-error` either in years of using Emacs, nor have I ever been asked before to add `flycheck-last-error` in almost three years that Flycheck exists now.

Closing as `wontfix`.  Sorry.

**Comment by wbolster** [comment]
hmmm yes, i can agree with that reasoning. i am a recent vim to evil convert, so bear with me. 😉

i'll define my own functions (per your suggestion) for my keymaps. thanks for the useful explanation!

**Comment by lunaryorn** [comment]
@wbolster You're welcome.  Thank you for understanding and accepting our point of view :blush:

**Comment by wbolster** [comment]
i'm all for minimal code bases with simple extensibility. i just don't have a good intuition yet for what is considered "bloat" for an editor ecosystem that's almost a complete os. 😉

    — wouter

-- 
sent from my phone. please forgive my tpyos.
