### ISSUE TITLE
Is there a nice way to try multiple checker commands?

### ISSUE THREAD

**Issue by themattchan** [flycheck/flycheck#930]
Hi, 

I'm trying to augment the Liquid Haskell checker (https://github.com/themattchan/flycheck-liquidhs.el) to support stack, with regular ghci as fallback. Is there a way to do this in the same :command field?

Thanks in advance!

**Comment by lunaryorn** [comment]
I do not know what "support stack" involves, hence I can only give common place answers:  You can evaluate arbitrary expressions in `:command` with the `eval` cell, and thus splice arbitrary arguments with arbitrary conditions into the command.  However, you cannot use `eval` at the beginning of `:command` because Flycheck expects a fixed executable name there.

Generally, though, you can always use `flycheck-command-wrapper-function` to apply arbitrary transformations to the command list.  However, if you do so you must make sure that the transformation leads to a proper command that is executable.  Otherwise Flycheck will error.

**Comment by lunaryorn** [comment]
@themattchan Are there any open questions left?  What's the state of this?

**Comment by lunaryorn** [comment]
Closing due to the lack of any activity.
