### ISSUE TITLE
Error while checking syntax automatically: (void-variable package-user-dir)

### ISSUE THREAD

**Issue by zw963** [flycheck/flycheck#946]
Emacs 24.5.

config:
```cl
(setq flycheck-disabled-checkers '(emacs-lisp-checkdoc))
(require 'flycheck)
(global-flycheck-mode)
```
When open a `.el` file, get those error message.

Thanks.

**Comment by Simplify** [comment]
Did you try to add `(package-initialize)` before your config?

**Comment by zw963** [comment]
Sorry,  comment out `(package-initilaize)`  because a irrelevant problem.

(BTW, I don't know package-initlaize is a dependency of flycheck, I only think it is part of melpa
initialize code, and I install flycheck manually completely, so, i think those maybe should
explain in README, or just skip emacs-lisp-mode fly-check if package-initialize is not run.)

Thanks very much.

**Comment by Simplify** [comment]
No, `(package-initialize)` is part of `package.el` that comes with Emacs. It's not dependency of Flycheck. Sorry if my question made any confusions.

**Comment by cpitclaudel** [comment]
I think the issue here is that flycheck reads package-user-dir in its emacs-lisp checker, which causes the error that @zw963 reported if `package.el` hasn't been loaded. Running `(package-initialize)` has the side effect of loading `package.el`.  Hence the connection.

@lunaryorn, should the emacs-lisp checker `(require 'package)`?

**Comment by lunaryorn** [comment]
@cpitclaudel I wrapped `package-user-dir` in `bound-and-true-p` which should prevent this issue in future.

@zw963 `(package-initialize)` is an (implicit) dependency of **any** package you install from MELPA, because prior to `(package-initialize)` packages are not even in `load-path`.  In other words without `(package-initialise)` you wouldn't be able to `(require 'flycheck)` if you installed Flycheck from MELPA.

That's also why I'm somewhat surprised that your code in the first posting actually produced this issue if you installed Flycheck from MELPA.  That should literally be impossible.  You don't happen to have another version of `flycheck.el` lingering somewhere in your `load-path`?  Or didn't you install Flycheck from MELPA?

**Comment by cpitclaudel** [comment]
@lunaryorn Neat, thanks! If I understood correctly, @zw963 installed Flycheck manually.

**Comment by cpitclaudel** [comment]
In any case, thanks @zw963 for the report!

**Comment by zw963** [comment]
> (package-initialize) is an (implicit) dependency of any package you install from MELPA, because prior to (package-initialize) packages are not even in load-path.

I settings ELPA correctly in my dotfiles, But, I never use ELPA installed package in my dotfiles, generally, I install package from github or emacs-wiki manually. (just download, copy, and add some snippets in my dotfiles), I think maybe exist others emacs fans like me. : )

Only one case i use ELPA package, some package could not found by Google (e.g. too old), I will install from ELPA, and copy files from elpa cache to my package directory,  still write dotfiles manually by myself, if it work correct, i will remove ELPA cache directory manually.


> That should literally be impossible. You don't happen to have another version of flycheck.el lingering somewhere in your load-path? Or didn't you install Flycheck from MELPA?

load-path is settings by myself, but automatically. following code, will correct settings my dotfiles default directory's and all subdirectory into load path.

file: init.el

```cl
(setq default-directory (file-name-directory (or load-file-name buffer-file-name)))
(normal-top-level-add-subdirs-to-load-path)
```
What i need is just create  {init.el directory}/plugins/flychek directory, and copy all need package into it.
then add my dotfiles.

Thanks.

**Comment by lunaryorn** [comment]
@zw963 I see.  Please be aware that we don't support manual installation, and that our source code tree as seen on Github is not intended to be added to `load-path` in its entirety.  We don't actively work against manual installation of Flycheck, but we don't test it and give no guarantees if you install manually.

In other words, use at your own risk, accept breakage if it occurs, and please understand that we'll not make any compromises in order to support manual installation.

**Comment by lunaryorn** [comment]
@zw963 Following this issue I added our [policy for alternative installation methods](http://www.flycheck.org/en/latest/user/installation.html#alternative-installation-methods) to our installation instructions.

**Comment by zw963** [comment]
Sorry for confuse, i just think install manually is more clearly for me.
