### ISSUE TITLE
Line number truncation in *Flycheck errors* buffer

### ISSUE THREAD

**Issue by fice-t** [flycheck/flycheck#977]
When the line number of the error/warning is > 4, then the number gets truncated (e.g. 1... instead of 10000). It would be nice if the column's width was determined dynamically (or interactively changeable) to prevent this.

`Flycheck version: 28snapshot (package: 20160518.111)`

**Comment by lunaryorn** [comment]
Thank you for reporting this problem.  Would you like to try and implement your preferred solution and open a pull request?

**Comment by fice-t** [comment]
Well, the following changed function seems to work (needs `flycheck-error-list-format` to be changed to a defvar):
```elisp
(defun flycheck-error-list-entries ()
  "Create the entries for the error list."
  (-when-let* ((errors (flycheck-error-list-current-errors))
               (filtered (flycheck-error-list-apply-filter errors))
               (max-len (flycheck-error-line (car (last filtered)))))
    (setf (elt (aref flycheck-error-list-format 0)
               1)
          (max 4 (1+ (floor (log max-len 10)))))
    (seq-map #'flycheck-error-list-make-entry filtered)))
```
Which could be made more efficient. It also assumes the last error contains the highest line number; is that incorrect?

Perhaps a stopgap solution could be to introduce a variable for the width in `flycheck-error-list-format`, or just change the default line-column width from 4 to 5.

I noticed though that your `flycheck-error-list-mode` derives from the built-in `tabulated-list-mode`. Perhaps adjustable columns should instead be implemented upstream?

**Comment by lunaryorn** [comment]
@fice-t Sorry for replying late, seems that I forgot about this one.

The errors are sorted, but we shouldn't count on that.  It's not strictly required for Flycheck's internals and we might as well remove the sorting at some point.  Hence you'd need to iterate over all errors to find out the largest line number, but a simpler approach would probably just be `(max 4 (1+ (floor (log (line-number-at-pos (point-max)) 10))))`, i.e take as many digits as the highest line number in the buffer.

However, you must not modify elements of `flycheck-error-list-format` because that'd globally change the value of a `defconst`.  Although it'd not have an adverse effect as there's only one error list buffer at any time it's still bad style to modify constant values in Emacs Lisp.

In any case, I've increased the width of the column to 5 now.  If that's enough for you I don't think that we need to dynamically compute the width of the column.

**Comment by cpitclaudel** [comment]
I think increasing to 5 is pretty good. I'd be a bit worried about `(line-number-at-pos (point-max))`: it needs to iterate over all lines of the buffer, which could be pretty slow.

**Comment by fice-t** [comment]
5 is working good for me so far. While dynamic-width columns would be nice, I don't think it's much of an issue now.

It appears that there's already a [feature request](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=21932) for this on the Emacs side for `tabulated-list-mode`.

**Comment by cpitclaudel** [comment]
@fice-t I have unbounded admiration for people who manage to find things in the Emacs bugs list.

**Comment by lunaryorn** [comment]
I think we can consider this closed then.
